/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 16:22:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class branch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".si_img {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 100%; /* 필요한 경우 조정 */\r\n");
      out.write("	height: 300px; /* 필요한 경우 조정 */\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".si_img a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".si_img_bg {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	object-fit: cover; /* 이 속성을 사용하면 이미지가 컨테이너에 맞게 조정됩니다 */\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".si_img_border {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	border: 2px solid; /* 원하는 대로 조정 */\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header.jsp 내용 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/headerReservation.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\" class=\"reservation_wrap\">\r\n");
      out.write("		<div class=\"sub_visual\">\r\n");
      out.write("			<div class=\"sub_visual_bg\"\r\n");
      out.write("				style=\"background-image: url('https://www.junohair.com/static_resources/images/junohair/sub/reservation/reser_visual.jpg')\"></div>\r\n");
      out.write("			<div class=\"sub_visual_text\">\r\n");
      out.write("				<strong>RESERVATION</strong>\r\n");
      out.write("				<p class=\"sub_visual_sub_text\">\r\n");
      out.write("					<span>실시간 매장 예약을 통해 <br class=\"m\">편리한 매장 이용을 도와드리며,\r\n");
      out.write("					</span><br> <span>AI기반의 디자이너 추천 기능을 제공합니다.</span>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"contents\" class=\"shop_list\">\r\n");
      out.write("			<div class=\"reser_process\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"current\"><span class=\"num\">01</span> <span>매장선택</span></li>\r\n");
      out.write("					<li><span class=\"num\">02</span> <span>디자이너 선택</span></li>\r\n");
      out.write("					<li><span class=\"num\">03</span> <span>일정 및 시술 선택</span></li>\r\n");
      out.write("					<li><span class=\"num\">04</span> <span>예약 확인</span></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"shop_search\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<ul class=\"search_form\">\r\n");
      out.write("						<li class=\"area_sido\"><strong class=\"depth\"><a\r\n");
      out.write("								href=\"#juno\">광역시/도</a></strong>\r\n");
      out.write("							<div id=\"sidoList\" class=\"area_list_wrap\" style=\"display: none;\">\r\n");
      out.write("								<ul class=\"sido_list\">\r\n");
      out.write("									<li class=\"sido_item\" @click=\"selectedSido(sido)\"\r\n");
      out.write("										v-for=\"sido in sidoList\" :key=\"sido.sidoCode\">{{\r\n");
      out.write("										sido.sidoName }}</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"area_gugun\"><strong class=\"depth\"> <a\r\n");
      out.write("								href=\"#juno\">구/군</a></strong>\r\n");
      out.write("							<div id=\"gugunList\" class=\"area_list_wrap\" style=\"display: none;\">\r\n");
      out.write("								<ul class=\"gugun_list\">\r\n");
      out.write("									<li class=\"gugun_item\" @click=\"selectedGugun(gugun)\"\r\n");
      out.write("										v-for=\"gugun in gugunList\" :key=\"gugun.gugunCode\">{{\r\n");
      out.write("										gugun.gugunName }}</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li class=\"search_input\"><input type=\"text\"\r\n");
      out.write("							placeholder=\"지역 또는 매장을 입력하세요\"></li>\r\n");
      out.write("						<li class=\"search_btn\"><a href=\"#juno\"><img\r\n");
      out.write("								src=\"https://www.junohair.com/static_resources/images/junohair/sub/subMenu_search_btn.png\"\r\n");
      out.write("								alt=\"매장검색\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"clear\"></div>\r\n");
      out.write("			<div class=\"section\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<div class=\"shop_result\">\r\n");
      out.write("						<div class=\"shop_result_list\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"pagination\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<a href=\"#juno\" class=\"first\"> <i aria-hidden=\"true\"\r\n");
      out.write("										class=\"fa fa-caret-left\"></i> <i aria-hidden=\"true\"\r\n");
      out.write("										class=\"fa fa-caret-left\"></i>\r\n");
      out.write("									</a> <a href=\"#juno\" class=\"prev\"> <i aria-hidden=\"true\"\r\n");
      out.write("										class=\"fa fa-caret-left\"></i></a> <a href=\"#juno\" class=\"cur\">1</a>\r\n");
      out.write("									<a href=\"#juno\">2</a> <a href=\"#juno\">3</a> <a href=\"#juno\">4</a>\r\n");
      out.write("									<a href=\"#juno\">5</a> <a href=\"#juno\" class=\"next\"><i\r\n");
      out.write("										aria-hidden=\"true\" class=\"fa fa-caret-right\"></i></a> <a\r\n");
      out.write("										href=\"#juno\" class=\"last\"><i aria-hidden=\"true\"\r\n");
      out.write("										class=\"fa fa-caret-right\"></i> <i aria-hidden=\"true\"\r\n");
      out.write("										class=\"fa fa-caret-right\"></i></a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- footer.jsp 내용 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	var regionCode = {\r\n");
      out.write("		\"sidoList\" : [ {\r\n");
      out.write("			\"sidoName\" : \"광역시/도\",\r\n");
      out.write("			\"sidoCode\" : \"\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"sidoName\" : \"서울특별시\",\r\n");
      out.write("			\"sidoNameEn\" : \"Seoul\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"sidoName\" : \"경기도\",\r\n");
      out.write("			\"sidoNameEn\" : \"Gyeonggi-do\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"2\",\r\n");
      out.write("			\"sidoName\" : \"인천광역시\",\r\n");
      out.write("			\"sidoNameEn\" : \"Incheon\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"6\",\r\n");
      out.write("			\"sidoName\" : \"울산광역시\",\r\n");
      out.write("			\"sidoNameEn\" : \"Ulsan\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"7\",\r\n");
      out.write("			\"sidoName\" : \"부산광역시\",\r\n");
      out.write("			\"sidoNameEn\" : \"Busan\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"10\",\r\n");
      out.write("			\"sidoName\" : \"충청북도\",\r\n");
      out.write("			\"sidoNameEn\" : \"Chungcheongbuk-do\"\r\n");
      out.write("		} ],\r\n");
      out.write("		\"gugunList\" : [ {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"1\",\r\n");
      out.write("			\"gugunName\" : \"강남구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gangnam-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"2\",\r\n");
      out.write("			\"gugunName\" : \"강동구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gangdong-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"3\",\r\n");
      out.write("			\"gugunName\" : \"강북구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gangbuk-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"4\",\r\n");
      out.write("			\"gugunName\" : \"강서구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gangseo-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"5\",\r\n");
      out.write("			\"gugunName\" : \"관악구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gwanak-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"6\",\r\n");
      out.write("			\"gugunName\" : \"광진구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gwangjin-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"7\",\r\n");
      out.write("			\"gugunName\" : \"구로구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Guro-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"8\",\r\n");
      out.write("			\"gugunName\" : \"금천구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Geumcheon-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"9\",\r\n");
      out.write("			\"gugunName\" : \"노원구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Nowon-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"11\",\r\n");
      out.write("			\"gugunName\" : \"동대문구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Dongdaemun-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"12\",\r\n");
      out.write("			\"gugunName\" : \"동작구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Dongjak-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"13\",\r\n");
      out.write("			\"gugunName\" : \"마포구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Mapo-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"14\",\r\n");
      out.write("			\"gugunName\" : \"서대문구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Seodaemun-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"15\",\r\n");
      out.write("			\"gugunName\" : \"서초구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Seocho-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"16\",\r\n");
      out.write("			\"gugunName\" : \"성동구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Seongdong-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"17\",\r\n");
      out.write("			\"gugunName\" : \"성북구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Seongbuk-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"18\",\r\n");
      out.write("			\"gugunName\" : \"송파구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Songpa-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"19\",\r\n");
      out.write("			\"gugunName\" : \"양천구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Yangcheon-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"20\",\r\n");
      out.write("			\"gugunName\" : \"영등포구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Yeongdeungpo-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"21\",\r\n");
      out.write("			\"gugunName\" : \"용산구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Yongsan-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"22\",\r\n");
      out.write("			\"gugunName\" : \"은평구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Eunpyeong-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"23\",\r\n");
      out.write("			\"gugunName\" : \"종로구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Jongno-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"24\",\r\n");
      out.write("			\"gugunName\" : \"중구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Jung-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"1\",\r\n");
      out.write("			\"gugunCode\" : \"25\",\r\n");
      out.write("			\"gugunName\" : \"중랑구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Jungnang-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"10\",\r\n");
      out.write("			\"gugunCode\" : \"2\",\r\n");
      out.write("			\"gugunName\" : \"청주시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Cheongju-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"2\",\r\n");
      out.write("			\"gugunCode\" : \"4\",\r\n");
      out.write("			\"gugunName\" : \"남동구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Namdong-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"2\",\r\n");
      out.write("			\"gugunCode\" : \"8\",\r\n");
      out.write("			\"gugunName\" : \"연수구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Yeonsu-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"6\",\r\n");
      out.write("			\"gugunCode\" : \"1\",\r\n");
      out.write("			\"gugunName\" : \"남구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Nam-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"7\",\r\n");
      out.write("			\"gugunCode\" : \"6\",\r\n");
      out.write("			\"gugunName\" : \"부산진구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Busanjin-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"7\",\r\n");
      out.write("			\"gugunCode\" : \"12\",\r\n");
      out.write("			\"gugunName\" : \"연제구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Yeonje-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"7\",\r\n");
      out.write("			\"gugunCode\" : \"15\",\r\n");
      out.write("			\"gugunName\" : \"해운대구\",\r\n");
      out.write("			\"gugunNameEn\" : \"Haeundae-gu\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"1\",\r\n");
      out.write("			\"gugunName\" : \"고양시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Goyang-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"3\",\r\n");
      out.write("			\"gugunName\" : \"광명시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gwangmyeong-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"5\",\r\n");
      out.write("			\"gugunName\" : \"구리시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Guri-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"7\",\r\n");
      out.write("			\"gugunName\" : \"김포시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Gimpo-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"8\",\r\n");
      out.write("			\"gugunName\" : \"남양주시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Namyangju-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"10\",\r\n");
      out.write("			\"gugunName\" : \"부천시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Bucheon-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"11\",\r\n");
      out.write("			\"gugunName\" : \"성남시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Seongnam-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"12\",\r\n");
      out.write("			\"gugunName\" : \"수원시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Suwon-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"13\",\r\n");
      out.write("			\"gugunName\" : \"시흥시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Siheung-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"14\",\r\n");
      out.write("			\"gugunName\" : \"안산시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Ansan-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"19\",\r\n");
      out.write("			\"gugunName\" : \"용인시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Yongin-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"23\",\r\n");
      out.write("			\"gugunName\" : \"파주시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Paju-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"26\",\r\n");
      out.write("			\"gugunName\" : \"하남시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Hanam-si\"\r\n");
      out.write("		}, {\r\n");
      out.write("			\"sidoCode\" : \"8\",\r\n");
      out.write("			\"gugunCode\" : \"27\",\r\n");
      out.write("			\"gugunName\" : \"화성시\",\r\n");
      out.write("			\"gugunNameEn\" : \"Hwaseong-si\"\r\n");
      out.write("		} ]\r\n");
      out.write("	}\r\n");
      out.write("	var shopListSearchParams = {\r\n");
      out.write("		\"sidoCode\" : \"\",\r\n");
      out.write("		\"sidoName\" : \"광역시/도\",\r\n");
      out.write("		\"gugunCode\" : \"\",\r\n");
      out.write("		\"gugunName\" : \"구/군\",\r\n");
      out.write("		\"srcValue\" : \"\",\r\n");
      out.write("		\"pageNo\" : \"1\"\r\n");
      out.write("	}\r\n");
      out.write("	var app = new Vue(\r\n");
      out.write("			{\r\n");
      out.write("				el : \"#contents\",\r\n");
      out.write("				data : {\r\n");
      out.write("					sidoName : shopListSearchParams.sidoName,\r\n");
      out.write("					sidoCode : shopListSearchParams.sidoCode,\r\n");
      out.write("					gugunName : shopListSearchParams.gugunName,\r\n");
      out.write("					gugunCode : shopListSearchParams.gugunCode,\r\n");
      out.write("					sidoList : regionCode.sidoList,\r\n");
      out.write("					gugunList : [],\r\n");
      out.write("					srcValue : shopListSearchParams.srcValue,\r\n");
      out.write("					dataList : [],\r\n");
      out.write("					pageNo : shopListSearchParams.pageNo,\r\n");
      out.write("					pageInfo : {},\r\n");
      out.write("					pageSize : 10, // 페이지 크기 설정\r\n");
      out.write("				},\r\n");
      out.write("				mounted: function() {\r\n");
      out.write("					\r\n");
      out.write(" 			        selectedSido: function(sido) {\r\n");
      out.write("			            $(\"#sidoList\").hide();\r\n");
      out.write("			            this.sidoName = sido.sidoName;\r\n");
      out.write("			            this.sidoCode = sido.sidoCode;\r\n");
      out.write("			            this.gugunName = \"구/군\";\r\n");
      out.write("			            this.gugunCode = \"\";\r\n");
      out.write("			            this.gugunList = [];\r\n");
      out.write("			            this.gugunList.addElement(0, {\r\n");
      out.write("			                gugunName: \"구/군\",\r\n");
      out.write("			                gugunCode: \"\"\r\n");
      out.write("			            });\r\n");
      out.write("			            for (var i = 0; i < regionCode.gugunList.length; i++) {\r\n");
      out.write("			                if (regionCode.gugunList[i].sidoCode == this.sidoCode) {\r\n");
      out.write("			                    this.gugunList.push(regionCode.gugunList[i]);\r\n");
      out.write("			                }\r\n");
      out.write("			            }\r\n");
      out.write("			            this.goInitSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			        selectedGugun: function(gugun) {\r\n");
      out.write("			            $(\"#gugunList\").hide();\r\n");
      out.write("			            this.gugunName = gugun.gugunName;\r\n");
      out.write("			            this.gugunCode = gugun.gugunCode;\r\n");
      out.write("			            this.goInitSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			        goInitSearch: function() {\r\n");
      out.write("			            this.pageNo = 1;\r\n");
      out.write("			            this.goSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			        goSearch: function() {\r\n");
      out.write("			            var params = {\r\n");
      out.write("			                sidoCode: this.sidoCode,\r\n");
      out.write("			                sidoName: this.sidoName,\r\n");
      out.write("			                gugunCode: this.gugunCode,\r\n");
      out.write("			                gugunName: this.gugunName,\r\n");
      out.write("			                srcValue: this.srcValue.trim(),\r\n");
      out.write("			                pageNo: this.pageNo,\r\n");
      out.write("			                pageSize: this.pageSize  // 페이지 크기 전달\r\n");
      out.write("			            }\r\n");
      out.write("			            cf_call(\"/junohair/salon/getShopList\", params, this.goSearchCB);\r\n");
      out.write("			        },\r\n");
      out.write("			        goSearchCB: function(data) {\r\n");
      out.write("			            if (data.errMsg != undefined) {\r\n");
      out.write("			                alert(data.errMsg);\r\n");
      out.write("			                return;\r\n");
      out.write("			            }\r\n");
      out.write("			            this.dataList = data.list;\r\n");
      out.write("			            this.pageInfo = data.pageInfo;\r\n");
      out.write("			            $(\".vue-contents-container\").show();\r\n");
      out.write("			        }, */\r\n");
      out.write("			        goView: function(data) {\r\n");
      out.write("			            location.href = \"/junohair/salon/shop_info?idx=\" + data.idx;\r\n");
      out.write("			        },\r\n");
      out.write("			        goReserve: function(cpcode) {\r\n");
      out.write("			            location.href = \"/junohair/reservation/process02_designer?cpcode=\" + cpcode;\r\n");
      out.write("			        },\r\n");
      out.write("			        gotoPage: function(pageNo) {\r\n");
      out.write("			            this.pageNo = pageNo;\r\n");
      out.write("			            this.goSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			        gotoFirstPage: function() {\r\n");
      out.write("			            this.pageNo = 1;\r\n");
      out.write("			            this.goSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			        gotoPreBlock: function() {\r\n");
      out.write("			            var preBlockPageNo = this.pageInfo.preBlockPageNo;\r\n");
      out.write("			            if (preBlockPageNo != -1) {\r\n");
      out.write("			                this.pageNo = preBlockPageNo;\r\n");
      out.write("			            }\r\n");
      out.write("			            this.goSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			        gotoNextBlock: function() {\r\n");
      out.write("			            var nextBlockPageNo = this.pageInfo.nextBlockPageNo;\r\n");
      out.write("			            if (nextBlockPageNo != -1) {\r\n");
      out.write("			                this.pageNo = nextBlockPageNo;\r\n");
      out.write("			            }\r\n");
      out.write("			            this.goSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			        gotoLastPage: function() {\r\n");
      out.write("			            this.pageNo = this.pageInfo.totalPages;\r\n");
      out.write("			            this.goSearch();\r\n");
      out.write("			        },\r\n");
      out.write("			    }\r\n");
      out.write("			});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/reservation/branch.jsp(104,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("branch");
      // /WEB-INF/views/reservation/branch.jsp(104,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/reservation/branch.jsp(104,7) '${branch}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${branch}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<div class=\"shop_item\">\r\n");
            out.write("									<div class=\"si_img\">\r\n");
            out.write("										<a href=\"#juno\"> <img class=\"si_img_bg\"\r\n");
            out.write("											src=\"./resources/productupload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.branchPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("											<div class=\"si_img_border\"></div>\r\n");
            out.write("										</a>\r\n");
            out.write("									</div>\r\n");
            out.write("									<div class=\"si_info\">\r\n");
            out.write("										<div class=\"si_info_inner\">\r\n");
            out.write("											<a href=\"#juno\"> <strong>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.branchName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</strong>\r\n");
            out.write("												<p>\r\n");
            out.write("													<span>주소:</span><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("												</p>\r\n");
            out.write("												<p>\r\n");
            out.write("													<span>영업:</span><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.openingTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("												</p>\r\n");
            out.write("												<p>\r\n");
            out.write("													<span>주차:</span><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.parking}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("												</p>\r\n");
            out.write("												<p>\r\n");
            out.write("													<span>전화:</span><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.contact}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("												</p>\r\n");
            out.write("											</a>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("									<div class=\"si_reservation\">\r\n");
            out.write("										<a href=\"designer?branchId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.branchId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("											<div>\r\n");
            out.write("												<img\r\n");
            out.write("													src=\"https://www.junohair.com/static_resources/images/junohair/sub/junohair/shopList_res_dark.png\"\r\n");
            out.write("													alt=\"예약\" class=\"dark\"> <img\r\n");
            out.write("													src=\"https://www.junohair.com/static_resources/images/junohair/sub/junohair/shopList_res_light.png\"\r\n");
            out.write("													alt=\"예약\" class=\"light\"> <span>예약하기</span>\r\n");
            out.write("											</div>\r\n");
            out.write("										</a>\r\n");
            out.write("									</div>\r\n");
            out.write("									<span class=\"mline\"></span>\r\n");
            out.write("								</div>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
