/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 16:24:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    // JSTL을 사용하여 userId를 JavaScript 변수에 할당\r\n");
      out.write("    const userId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    console.log(\"User ID: \", userId); // userId 값을 콘솔에 출력\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<!-- jQuery CDN 링크 추가 -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- header.jsp 내용 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/headerReservation.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\" class=\"reservation_wrap\">\r\n");
      out.write("	<div class=\"sub_visual\">\r\n");
      out.write("		<div class=\"sub_visual_bg\"\r\n");
      out.write("			style=\"background-image: url('https://www.junohair.com/static_resources/images/junohair/sub/reservation/reser_visual.jpg')\"></div>\r\n");
      out.write("		<div class=\"sub_visual_text\">\r\n");
      out.write("			<strong>RESERVATION</strong>\r\n");
      out.write("			<p class=\"sub_visual_sub_text\">\r\n");
      out.write("				<span>실시간 매장 예약을 통해 <br class=\"m\">편리한 매장 이용을 도와드리며,\r\n");
      out.write("				</span><br> <span>AI기반의 디자이너 추천 기능을 제공합니다.</span>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"contents\" class=\"shop_list\">\r\n");
      out.write("		<div class=\"reser_process\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><span class=\"num\">01</span> <span>매장 선택</span></li>\r\n");
      out.write("				<li style=\"cursor: pointer;\" onclick=\"gotoPre()\"><span\r\n");
      out.write("					class=\"num\">02</span> <span>디자이너 선택</span></li>\r\n");
      out.write("				<li class=\"current\"><span class=\"num\">03</span> <span>일정\r\n");
      out.write("						및 시술 선택</span></li>\r\n");
      out.write("				<li><span class=\"num\">04</span> <span>예약 확인</span></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"clear\"></div>\r\n");
      out.write("	<!-- 선택한 디자이너 및 지점 Info 출력 -->\r\n");
      out.write("	<div class=\"designer_namebox\">\r\n");
      out.write("		<p class=\"profileimg\">\r\n");
      out.write("			 <!-- <img src=\"./resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designerInfo.designerPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" -->\r\n");
      out.write("			<img src=\"./resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designerInfo.designerPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("             class=\"profileimgsrc\"\r\n");
      out.write("             style=\"width: 150px; height: 125px; object-fit: cover;\">\r\n");
      out.write("		</p>\r\n");
      out.write("		<div class=\"infocont\">\r\n");
      out.write("			<p class=\"ttl\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designerInfo.designerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<em>-</em> <span\r\n");
      out.write("					class=\"branch\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branchInfo.branchName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p class=\"desc\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designerInfo.introduce}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<span class=\"line\"></span>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 달력 form -->\r\n");
      out.write("	<div class=\"schedule_box\">\r\n");
      out.write("		<div class=\"calendar_wrap\">\r\n");
      out.write("			<div class=\"head\">\r\n");
      out.write("				<a class=\"btn_prev\" href=\"designer?branchId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch.branchId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("					onclick=\"prevCal()\"><span class=\"blind\">이전</span></a> <span\r\n");
      out.write("					class=\"title_month\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentMonth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> <a class=\"btn_next\"\r\n");
      out.write("					href=\"reservationConfirm\" onclick=\"nextCal()\"><span\r\n");
      out.write("					class=\"blind\">다음</span></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"calendarTable\">\r\n");
      out.write("				<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th class=\"sun\">일</th>\r\n");
      out.write("							<th>월</th>\r\n");
      out.write("							<th>화</th>\r\n");
      out.write("							<th>수</th>\r\n");
      out.write("							<th>목</th>\r\n");
      out.write("							<th>금</th>\r\n");
      out.write("							<th class=\"sat\">토</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<tbody id=\"caltbody\">\r\n");
      out.write("						<!-- 현재 월 달력 -->\r\n");
      out.write("						<div id=\"currentMonthCalendar\" style=\"display: block;\">\r\n");
      out.write("							<h1 id=\"currentMonth\" style=\"text-align:\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentMonth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("							<div class=\"calendarContainer\">\r\n");
      out.write("								<table class=\"uniqueCalendarTable\">\r\n");
      out.write("									");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"timeselectbox\">\r\n");
      out.write("						<div class=\"dateTime\">\r\n");
      out.write("							<p class=\"tit\">날짜</p>\r\n");
      out.write("							<p class=\"txt\" id=\"dateTimeTxt\">날짜를 선택해주세요.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dateTime\">\r\n");
      out.write("							<p class=\"tit\">시간</p>\r\n");
      out.write("							<p class=\"txt\" id=\"timeselect\">시간을 선택해주세요.</p>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"timeline\" id=\"timeline\">\r\n");
      out.write("							<div class=\"timesec\">\r\n");
      out.write("								<p class=\"tit\">오전</p>\r\n");
      out.write("								<ul id=\"morningTimeList\">\r\n");
      out.write("									<!-- 오전 시간대가 JavaScript로 채워집니다 -->\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timesec\">\r\n");
      out.write("								<div class=\"line\">\r\n");
      out.write("									<span></span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"tit\">오후</p>\r\n");
      out.write("								<ul id=\"afternoonTimeList\">\r\n");
      out.write("									<!-- 오후 시간대가 JavaScript로 채워집니다 -->\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	<form>\r\n");
      out.write("	<!-- 시술 선택 및 예약 확인 화면 -->\r\n");
      out.write("	<div class=\"sisul_categorybox\">\r\n");
      out.write("	    <div class=\"sisul_category cover_scroll\">\r\n");
      out.write("	        <ul>\r\n");
      out.write("	            <li class=\"active\"><a href=\"#juno\" id=\"shampu\" onclick=\"selectSisulCategory('shampu')\">샴푸</a></li>\r\n");
      out.write("	            <li><a href=\"#juno\" id=\"dry\" onclick=\"selectSisulCategory('dry')\">드라이</a></li>\r\n");
      out.write("	            <li><a href=\"#juno\" id=\"cut\" onclick=\"selectSisulCategory('cut')\">커트</a></li>\r\n");
      out.write("	            <li><a href=\"#juno\" id=\"perm\" onclick=\"selectSisulCategory('perm')\">펌</a></li>\r\n");
      out.write("	            <li><a href=\"#juno\" id=\"color\" onclick=\"selectSisulCategory('color')\">컬러</a></li>\r\n");
      out.write("	            <li><a href=\"#juno\" id=\"clinic\" onclick=\"selectSisulCategory('clinic')\">클리닉</a></li>\r\n");
      out.write("	            <li><a href=\"#juno\" id=\"headspa\" onclick=\"selectSisulCategory('headspa')\">헤드스파</a></li>\r\n");
      out.write("	        </ul>\r\n");
      out.write("	        <span class=\"cover left\"></span>\r\n");
      out.write("	        <span class=\"cover right\"></span>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"sisul_category_detail sisul_cate_items\">\r\n");
      out.write("	    <ul id=\"sisuldetails\">\r\n");
      out.write("	        <!-- 시술 목록은 JavaScript로 채워집니다 -->\r\n");
      out.write("	    </ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"recomm_sisul\" id=\"recomm_sisul\" style=\"display: none;\"></div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"forecast_sisul\" style=\"display: none\">\r\n");
      out.write("	    <div class=\"box\">\r\n");
      out.write("	        <p class=\"ttl\">선택 내역</p>\r\n");
      out.write("	        <div class=\"mysisul\">\r\n");
      out.write("	            <ul id=\"mysisullist\"></ul>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Hidden Form -->\r\n");
      out.write("    <form id=\"reservationForm\" method=\"post\" action=\"reservationConfirm\">\r\n");
      out.write("        <input type=\"hidden\" name=\"reservationDate\" id=\"reservationDate\">\r\n");
      out.write("        <input type=\"hidden\" name=\"reservationTime\" id=\"reservationTime\">\r\n");
      out.write("        <input type=\"hidden\" name=\"sisul\" id=\"sisul\">\r\n");
      out.write("        <input type=\"hidden\" name=\"userId\" value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"branchId\" value=\"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"designerId\" value=\"");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("	<!-- <div class=\"sisul_textbox\">\r\n");
      out.write("		<textarea id=\"orderMemo\" placeholder=\"요청사항을 입력하세요 (150자 이내)\"></textarea>\r\n");
      out.write("	</div> -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"ai_foot_btns\">\r\n");
      out.write("	    <a href=\"javascript:gotoPre();\" class=\"btnbox_line\">이전</a> \r\n");
      out.write("	    <a href=\"javascript:submitReservation();\" class=\"btnbox_black\">다음</a>\r\n");
      out.write("	    <br><br><br>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer.jsp 내용 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"loading\" style=\"display: none;\">\r\n");
      out.write("	<div class=\"loading_inner\">\r\n");
      out.write("		<img src=\"/static_resources/images/gate_img1.png\" alt=\"JUNO HAIR\">\r\n");
      out.write("		<p>시간스케줄을 로딩중 입니다..</p>\r\n");
      out.write("		<div class=\"loading_dots\">\r\n");
      out.write("			<span class=\"loading_dot active\"></span> <span\r\n");
      out.write("				class=\"loading_dot active\"></span> <span class=\"loading_dot active\"></span>\r\n");
      out.write("			<span class=\"loading_dot active\"></span> <span\r\n");
      out.write("				class=\"loading_dot active\"></span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("let dayOutter = ''\r\n");
      out.write("function selectDay(day) {\r\n");
      out.write("	console.log(\"selectDay 함수 호출됨 / day:\", day);\r\n");
      out.write("	 const daysOfWeek = ['일', '월', '화', '수', '목', '금', '토'];\r\n");
      out.write("	 dayOutter=day;\r\n");
      out.write("	    // 현재 연도와 월을 가져옴\r\n");
      out.write("	    const currentMonth = '");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("	    const [year, month] = currentMonth.split('-');\r\n");
      out.write("\r\n");
      out.write("	    // 선택된 날짜를 조합\r\n");
      out.write("	    const selectedDate = year + '.' + (month.length === 1 ? '0' + month : month) + '.' + (day.length === 1 ? '0' + day : day);\r\n");
      out.write("\r\n");
      out.write("	    // 요일을 계산\r\n");
      out.write("	    const date = new Date(year, month - 1, day);\r\n");
      out.write("	    const dayOfWeek = daysOfWeek[date.getDay()];\r\n");
      out.write("\r\n");
      out.write("	    document.getElementById(\"dateTimeTxt\").textContent = selectedDate + '(' + dayOfWeek + ')';\r\n");
      out.write("	 	\r\n");
      out.write("	    // 예약 가능한 시간대를 서버에서 가져와서 업데이트\r\n");
      out.write("        fetchBookedTimes(year, month, day);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fetchBookedTimes(year, month, day) {\r\n");
      out.write("    const designerId = '");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("    const reservationDate = year + '-' + month + '-' + day;\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getBookedTimes',\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        data: {\r\n");
      out.write("            designerId: designerId,\r\n");
      out.write("            reservationDate: reservationDate\r\n");
      out.write("        },\r\n");
      out.write("        success: function(response) {\r\n");
      out.write("        	console.log('AJAX 요청 성공: ', response);\r\n");
      out.write("            updateTimelines(response);\r\n");
      out.write("        },\r\n");
      out.write("        error: function(xhr, status, error) {\r\n");
      out.write("            console.error('AJAX 에러: ', error);\r\n");
      out.write("            console.error('xhr: ', xhr);\r\n");
      out.write("            console.error('status: ', status);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateTimelines(bookedTimes) {\r\n");
      out.write("    const morningTimes = ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30'];\r\n");
      out.write("    const afternoonTimes = ['12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30'];\r\n");
      out.write("\r\n");
      out.write(" 	\r\n");
      out.write("    let morningHtml = '';\r\n");
      out.write("    for (let time of morningTimes) {\r\n");
      out.write("    	console.log(\"morningTimes: \", morningTimes);\r\n");
      out.write("        if (bookedTimes.includes(time)) {\r\n");
      out.write("        	console.log(\"bookedTimes: \", bookedTimes);\r\n");
      out.write("            morningHtml += '<li><span class=\"disabled\">' + time + '</span></li>';\r\n");
      out.write("        } else {\r\n");
      out.write("            morningHtml += '<li><a href=\"#juno\" time24=\"' + time + '\" ampm=\"am\" time=\"' + time + '\" onclick=\"selectTime(\\'' + time + '\\')\">' + time + '</a></li>';\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    console.log(\"morningHtml: \", morningHtml); // 데이터 확인\r\n");
      out.write("    document.getElementById(\"morningTimeList\").innerHTML = morningHtml;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    let afternoonHtml = '';\r\n");
      out.write("    for (let time of afternoonTimes) {\r\n");
      out.write("        if (bookedTimes.includes(time.trim())) {\r\n");
      out.write("            afternoonHtml += '<li><span class=\"disabled\">' + time + '</span></li>';\r\n");
      out.write("        } else {\r\n");
      out.write("            afternoonHtml += '<li><a href=\"#juno\" time24=\"' + time + '\" ampm=\"pm\" time=\"' + time + '\" onclick=\"selectTime(\\'' + time + '\\')\">' + time + '</a></li>';\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    console.log(\"afternoonHtml: \", afternoonHtml); // 데이터 확인\r\n");
      out.write("    document.getElementById(\"afternoonTimeList\").innerHTML = afternoonHtml;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function selectTime(time) {\r\n");
      out.write("    document.getElementById(\"timeselect\").textContent = time;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var sisulShampuList = [ {\r\n");
      out.write("  \"id\" : \"35c3358b1df396df765f57780b57f710\",\r\n");
      out.write("  \"sisulId\" : \"24ad48bab64d4e4fabd6912a6369ff02\",\r\n");
      out.write("  \"sisulDesc\" : \"릴렉싱 샴푸\",\r\n");
      out.write("  \"price\" : \"20,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 1\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"118170444885ba63df355aa31769bcf9\",\r\n");
      out.write("  \"sisulId\" : \"24ad48bab64d4e4fabd6912a6369ff02\",\r\n");
      out.write("  \"sisulDesc\" : \"성형 샴푸\",\r\n");
      out.write("  \"price\" : \"30,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 2\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"7d5336290f25d6c4c6d1c273f9754d35\",\r\n");
      out.write("  \"sisulId\" : \"24ad48bab64d4e4fabd6912a6369ff02\",\r\n");
      out.write("  \"sisulDesc\" : \"붙임머리 샴푸\",\r\n");
      out.write("  \"price\" : \"40,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 3\r\n");
      out.write("} ]\r\n");
      out.write("var sisulDryList = [ {\r\n");
      out.write("  \"id\" : \"fb605541afe4eb58aed92b42e0b63b03\",\r\n");
      out.write("  \"sisulId\" : \"b0109fa60f074135a219b0cc0c0b8170\",\r\n");
      out.write("  \"sisulDesc\" : \"블로우 드라이\",\r\n");
      out.write("  \"price\" : \"35,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 1\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"8955f534f9ec9f94268ad2228e35741e\",\r\n");
      out.write("  \"sisulId\" : \"b0109fa60f074135a219b0cc0c0b8170\",\r\n");
      out.write("  \"sisulDesc\" : \"아이롱 드라이\",\r\n");
      out.write("  \"price\" : \"45,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 2\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"510b8aa214d946d135b4aa033a47f327\",\r\n");
      out.write("  \"sisulId\" : \"b0109fa60f074135a219b0cc0c0b8170\",\r\n");
      out.write("  \"sisulDesc\" : \"붙임머리 드라이\",\r\n");
      out.write("  \"price\" : \"70,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 3\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"f469d198dd350b938afced608d0bd922\",\r\n");
      out.write("  \"sisulId\" : \"b0109fa60f074135a219b0cc0c0b8170\",\r\n");
      out.write("  \"sisulDesc\" : \"남성 스타일링\",\r\n");
      out.write("  \"price\" : \"20,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 4\r\n");
      out.write("} ]\r\n");
      out.write("var sisulCutList = [ {\r\n");
      out.write("  \"id\" : \"22c03bfcb95d7d22ddcc0781ebef2e4d\",\r\n");
      out.write("  \"sisulId\" : \"14b3341ceae44eddad06f20211e55506\",\r\n");
      out.write("  \"sisulDesc\" : \"앞머리 커트\",\r\n");
      out.write("  \"price\" : \"15,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 1\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"88932b8e7655a47087cc9cafebe4b9d6\",\r\n");
      out.write("  \"sisulId\" : \"14b3341ceae44eddad06f20211e55506\",\r\n");
      out.write("  \"sisulDesc\" : \"주니어 커트\",\r\n");
      out.write("  \"price\" : \"25,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 2\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"8f643a602afd813679952aa5ddf90d3a\",\r\n");
      out.write("  \"sisulId\" : \"14b3341ceae44eddad06f20211e55506\",\r\n");
      out.write("  \"sisulDesc\" : \"디자인 커트\",\r\n");
      out.write("  \"price\" : \"35,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 3\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"c7c972e51f04d5c751159a9ed4801fa8\",\r\n");
      out.write("  \"sisulId\" : \"14b3341ceae44eddad06f20211e55506\",\r\n");
      out.write("  \"sisulDesc\" : \"스켈링 커트\",\r\n");
      out.write("  \"price\" : \"75,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 4\r\n");
      out.write("} ]\r\n");
      out.write("var sisulPermList = [ {\r\n");
      out.write("  \"id\" : \"2fbd9558feaa454e1299f79da8caa385\",\r\n");
      out.write("  \"sisulId\" : \"cd2fd43703e34b42b63717a2e0ead06c\",\r\n");
      out.write("  \"sisulDesc\" : \"남성 베이직펌\",\r\n");
      out.write("  \"price\" : \"165,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 1\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"42a7301af0b56a4eb3c91c46811157bd\",\r\n");
      out.write("  \"sisulId\" : \"cd2fd43703e34b42b63717a2e0ead06c\",\r\n");
      out.write("  \"sisulDesc\" : \"여성 베이직펌\",\r\n");
      out.write("  \"price\" : \"200,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 2\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"2a6a574bcc6893545ee9d182506a7f2a\",\r\n");
      out.write("  \"sisulId\" : \"cd2fd43703e34b42b63717a2e0ead06c\",\r\n");
      out.write("  \"sisulDesc\" : \"셋팅 / 디지털 펌\",\r\n");
      out.write("  \"price\" : \"280,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 3\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"d9fb5a48a951c0f54a8d2277d393195c\",\r\n");
      out.write("  \"sisulId\" : \"cd2fd43703e34b42b63717a2e0ead06c\",\r\n");
      out.write("  \"sisulDesc\" : \"매직셋팅\",\r\n");
      out.write("  \"price\" : \"330,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 4\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"dc6c1e4d91c00cd8870ecc0517aee593\",\r\n");
      out.write("  \"sisulId\" : \"cd2fd43703e34b42b63717a2e0ead06c\",\r\n");
      out.write("  \"sisulDesc\" : \"다운펌\",\r\n");
      out.write("  \"price\" : \"40,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 5\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"4b906b09418ae6fb5ad4fd616d791545\",\r\n");
      out.write("  \"sisulId\" : \"cd2fd43703e34b42b63717a2e0ead06c\",\r\n");
      out.write("  \"sisulDesc\" : \"앞머리펌 / 부분펌\",\r\n");
      out.write("  \"price\" : \"44,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 6\r\n");
      out.write("} ]\r\n");
      out.write("var sisulColorList = [ {\r\n");
      out.write("  \"id\" : \"9df297ae72d02c27253f9f4ddc693d82\",\r\n");
      out.write("  \"sisulId\" : \"a640e8a9adc641949133642778707a14\",\r\n");
      out.write("  \"sisulDesc\" : \"리터치\",\r\n");
      out.write("  \"price\" : \"120,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 1\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"cfb05931e34d53cddafb130523a01a69\",\r\n");
      out.write("  \"sisulId\" : \"a640e8a9adc641949133642778707a14\",\r\n");
      out.write("  \"sisulDesc\" : \"베이직 염색\",\r\n");
      out.write("  \"price\" : \"165,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 2\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"234f81604e928a507971ea8eeb2bed53\",\r\n");
      out.write("  \"sisulId\" : \"a640e8a9adc641949133642778707a14\",\r\n");
      out.write("  \"sisulDesc\" : \"탈색\",\r\n");
      out.write("  \"price\" : \"187,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 3\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"b7c3e27e2eeb4affb3e1ae1906e57de3\",\r\n");
      out.write("  \"sisulId\" : \"a640e8a9adc641949133642778707a14\",\r\n");
      out.write("  \"sisulDesc\" : \"매니큐어\",\r\n");
      out.write("  \"price\" : \"165,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 4\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"a9cb833ae86f8cec4b5e4dc6bba48f4a\",\r\n");
      out.write("  \"sisulId\" : \"a640e8a9adc641949133642778707a14\",\r\n");
      out.write("  \"sisulDesc\" : \"하이라이트\",\r\n");
      out.write("  \"price\" : \"187,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 5\r\n");
      out.write("} ]\r\n");
      out.write("var sisulClinicList = [ {\r\n");
      out.write("  \"id\" : \"4a06e5a18ebd8b37a103c1122bc03361\",\r\n");
      out.write("  \"sisulId\" : \"b37a96feb9e041128ac70d8ec5b46f1c\",\r\n");
      out.write("  \"sisulDesc\" : \"이너 케어\",\r\n");
      out.write("  \"price\" : \"150,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 1\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"9ec54192a6275cf92c44d3143a7f86ae\",\r\n");
      out.write("  \"sisulId\" : \"b37a96feb9e041128ac70d8ec5b46f1c\",\r\n");
      out.write("  \"sisulDesc\" : \"인-아웃 케어\",\r\n");
      out.write("  \"price\" : \"200,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 2\r\n");
      out.write("}, {\r\n");
      out.write("  \"id\" : \"194d382e6627cf13453187caf1ab472c\",\r\n");
      out.write("  \"sisulId\" : \"b37a96feb9e041128ac70d8ec5b46f1c\",\r\n");
      out.write("  \"sisulDesc\" : \"프리미엄 케어\",\r\n");
      out.write("  \"price\" : \"250,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 3\r\n");
      out.write("} ]\r\n");
      out.write("var sisulHeadspaList = [ {\r\n");
      out.write("  \"id\" : \"53549336c45ea4303b76a5c4bc33f1b9\",\r\n");
      out.write("  \"sisulId\" : \"aa5d83e3f8744740b6708336ab94f7a8\",\r\n");
      out.write("  \"sisulDesc\" : \"두피 케어\",\r\n");
      out.write("  \"price\" : \"150,000\",\r\n");
      out.write("  \"priceDiscount\" : \"\",\r\n");
      out.write("  \"discountYn\" : false,\r\n");
      out.write("  \"recommendSisulId\" : \"\",\r\n");
      out.write("  \"sort\" : 1\r\n");
      out.write("} ]\r\n");
      out.write("var sisulAllList = sisulShampuList.concat(sisulDryList.concat(sisulCutList.concat(sisulPermList.concat(sisulColorList.concat(sisulClinicList.concat(sisulHeadspaList))))));\r\n");
      out.write("console.log(\"sisulAllList : \" + sisulAllList);\r\n");
      out.write("var selectedSisullist = [];\r\n");
      out.write("var totalamt;\r\n");
      out.write("var rdate;\r\n");
      out.write("var ryoil;\r\n");
      out.write("var rtime24;\r\n");
      out.write("var rtime;\r\n");
      out.write("var rampm;\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	todayCal();\r\n");
      out.write("	if(sisulShampuList.length != 0){\r\n");
      out.write("		selectSisulCategory(\"shampu\");\r\n");
      out.write("	} else if(sisulDryList.length != 0){\r\n");
      out.write("		selectSisulCategory(\"dry\");\r\n");
      out.write("	} else if(sisulCutList.length != 0){\r\n");
      out.write("		selectSisulCategory(\"cut\");\r\n");
      out.write("	} else if(sisulPermList.length != 0){\r\n");
      out.write("		selectSisulCategory(\"perm\");\r\n");
      out.write("	} else if(sisulColorList.length != 0){\r\n");
      out.write("		selectSisulCategory(\"color\");\r\n");
      out.write("	} else if(sisulClinicList.length != 0){\r\n");
      out.write("		selectSisulCategory(\"clinic\");\r\n");
      out.write("	} else {\r\n");
      out.write("		selectSisulCategory(\"headspa\");\r\n");
      out.write("	}\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function submitReservation() {\r\n");
      out.write("    const selectedSisulList = selectedSisullist; // 선택된 시술 목록을 가져오는 배열\r\n");
      out.write("    const reservationDateText = document.getElementById('dateTimeTxt').textContent; // 날짜 선택\r\n");
      out.write("    const reservationTime = document.getElementById('timeselect').textContent; // 시간 선택\r\n");
      out.write("\r\n");
      out.write("    // reservationDateText 형식을 \"YYYY.MM.DD(요일)\"에서 \"YYYY-MM-DD\"로 변환\r\n");
      out.write("    const datePattern = /\\d{4}\\.\\d{2}\\.\\d{2}/; // \"YYYY.MM.DD\" 패턴\r\n");
      out.write("    const dateMatch = reservationDateText.match(datePattern);\r\n");
      out.write("    const reservationDate = dateMatch[0].replace(/\\./g, '-'); // \"YYYY-MM-DD\" 형식으로 변환\r\n");
      out.write("\r\n");
      out.write("    const sisulString = selectedSisulList.map(sisul => sisul.sisulDesc).join(',');\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('reservationDate').value = reservationDate;\r\n");
      out.write("    document.getElementById('reservationTime').value = reservationTime;\r\n");
      out.write("    document.getElementById('sisul').value = sisulString; // 여기서 확인\r\n");
      out.write("\r\n");
      out.write("    console.log(\"Reservation Date: \", reservationDate);\r\n");
      out.write("    console.log(\"Reservation Time: \", reservationTime);\r\n");
      out.write("    console.log(\"Sisul String: \", sisulString); // 로그로 확인\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('reservationForm').submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("let selectedSisulList = [];\r\n");
      out.write("\r\n");
      out.write("function selectSisulCategory(sisulCategory) {\r\n");
      out.write("	console.log(\"selectSisulCategory들어옴\");\r\n");
      out.write("	console.log(\"sisulCategory\" + sisulCategory);\r\n");
      out.write("	\r\n");
      out.write("    var sisulCategoryList = $(\"#\" + sisulCategory).parent().parent().find(\"li\");\r\n");
      out.write("    for (var i = 0; i < sisulCategoryList.length; i++) {\r\n");
      out.write("        $(sisulCategoryList[i]).removeClass(\"active\");\r\n");
      out.write("    }\r\n");
      out.write("    $(\"#\" + sisulCategory).parent().addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("    var sisulList = [];\r\n");
      out.write("    if (sisulCategory === \"shampu\") {\r\n");
      out.write("        sisulList = sisulShampuList;\r\n");
      out.write("    } else if (sisulCategory === \"dry\") {\r\n");
      out.write("        sisulList = sisulDryList;\r\n");
      out.write("    } else if (sisulCategory === \"cut\") {\r\n");
      out.write("        sisulList = sisulCutList;\r\n");
      out.write("    } else if (sisulCategory === \"perm\") {\r\n");
      out.write("        sisulList = sisulPermList;\r\n");
      out.write("    } else if (sisulCategory === \"color\") {\r\n");
      out.write("        sisulList = sisulColorList;\r\n");
      out.write("    } else if (sisulCategory === \"clinic\") {\r\n");
      out.write("        sisulList = sisulClinicList;\r\n");
      out.write("    } else if (sisulCategory === \"headspa\") {\r\n");
      out.write("        sisulList = sisulHeadspaList;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(\"#sisuldetails\").html(\"\");\r\n");
      out.write("    var sisulListHtml = \"\";\r\n");
      out.write("    if (sisulList.length > 0) {\r\n");
      out.write("        for (var i = 0; i < sisulList.length; i++) {\r\n");
      out.write("            sisulListHtml += '<li>';\r\n");
      out.write("            sisulListHtml += '    <span class=\"check_type\">';\r\n");
      out.write("            sisulListHtml += '        <input type=\"checkbox\" id=\"' + sisulList[i].id + '\" class=\"checkbox\" onclick=\"sisulCheckboxOnclick(this);\"/>';\r\n");
      out.write("            sisulListHtml += '        <label for=\"' + sisulList[i].id + '\">' + sisulList[i].sisulDesc + '</label>';\r\n");
      out.write("            sisulListHtml += '    </span>';\r\n");
      out.write("            sisulListHtml += '    <div class=\"pricezone\">';\r\n");
      out.write("            if (sisulList[i].discountYn) {\r\n");
      out.write("                sisulListHtml += '        <p class=\"saleprice\">';\r\n");
      out.write("                sisulListHtml += '            <span class=\"original\">' + sisulList[i].price + '</span>';\r\n");
      out.write("                sisulListHtml += '            <span class=\"sale\">' + (100 - parseInt(Number(sisulList[i].priceDiscount.replaceAll(\",\", \"\")) / Number(sisulList[i].price.replaceAll(\",\", \"\")) * 100)) + '% 할인</span>';\r\n");
      out.write("                sisulListHtml += '        </p>';\r\n");
      out.write("                sisulListHtml += '        <p class=\"current\">' + sisulList[i].priceDiscount + '<span class=\"won\">원</span></p>';\r\n");
      out.write("                sisulListHtml += '    </div>';\r\n");
      out.write("                sisulListHtml += '</li>';\r\n");
      out.write("            } else {\r\n");
      out.write("                sisulListHtml += '        <p class=\"current\">' + sisulList[i].price + '<span class=\"won\">원</span></p>';\r\n");
      out.write("                sisulListHtml += '    </div>';\r\n");
      out.write("                sisulListHtml += '</li>';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    } else {\r\n");
      out.write("        sisulListHtml += '<li class=\"full\">시술 항목이 없습니다.</li>';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(\"#sisuldetails\").html(sisulListHtml);\r\n");
      out.write("\r\n");
      out.write("    // 각 시술상세의 체크박스 체크처리하기\r\n");
      out.write("    for (var i = 0; i < sisulAllList.length; i++) {\r\n");
      out.write("        if (sisulAllList[i].chk === true) {\r\n");
      out.write("            $(\"input:checkbox[id='\" + sisulAllList[i].id + \"']\").prop(\"checked\", true)\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sisulCheckboxOnclick(obj) {\r\n");
      out.write("    console.log(\"sisulCheckboxOnclick 들어옴\");\r\n");
      out.write("    console.log(\"obj: \", obj);\r\n");
      out.write("\r\n");
      out.write("    var sisulid = $(obj).attr('id');\r\n");
      out.write("    if ($(obj).prop('checked')) {\r\n");
      out.write("        for (var i = 0; i < sisulAllList.length; i++) {\r\n");
      out.write("            if (sisulid === sisulAllList[i].id) {\r\n");
      out.write("                sisulAllList[i].chk = true;\r\n");
      out.write("                selectedSisulList.push(sisulAllList[i]); // 선택된 시술상세 리스트에 추가\r\n");
      out.write("                break;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    } else {\r\n");
      out.write("        for (var i = 0; i < sisulAllList.length; i++) {\r\n");
      out.write("            if (sisulid === sisulAllList[i].id) {\r\n");
      out.write("                sisulAllList[i].chk = false;\r\n");
      out.write("                for (var j = 0; j < selectedSisulList.length; j++) {\r\n");
      out.write("                    if (sisulid === selectedSisulList[j].id) {\r\n");
      out.write("                        selectedSisulList.splice(j, 1); // 선택된 시술상세 리스트에서 삭제\r\n");
      out.write("                        break;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                break;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    setMysisulArea(); // 선택내역란 영역을 셋팅\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setMysisulArea() {\r\n");
      out.write("    console.log(\"setMysisulArea 들어옴\");\r\n");
      out.write("    $(\"#mysisullist\").html(\"\");\r\n");
      out.write("    var mysisullisthtml = \"\";\r\n");
      out.write("    for (var i = 0; i < selectedSisulList.length; i++) {\r\n");
      out.write("        mysisullisthtml += '<li>';\r\n");
      out.write("        mysisullisthtml += '    <span class=\"tit\">' + selectedSisulList[i].sisulDesc + '</span>';\r\n");
      out.write("        mysisullisthtml += '    <a href=\"#juno\" class=\"delete\" onclick=\"removeSelectedSisul(\\'' + selectedSisulList[i].id + '\\')\">삭제</a>';\r\n");
      out.write("        mysisullisthtml += '</li>';\r\n");
      out.write("    }\r\n");
      out.write("    $(\"#mysisullist\").html(mysisullisthtml);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function removeSelectedSisul(sisulid) {\r\n");
      out.write("    console.log(\"removeSelectedSisul 들어옴\");\r\n");
      out.write("    console.log(\"sisulid: \" + sisulid);\r\n");
      out.write("    $(\"input:checkbox[id='\" + sisulid + \"']\").prop(\"checked\", false);\r\n");
      out.write("    for (var i = 0; i < sisulAllList.length; i++) {\r\n");
      out.write("        if (sisulAllList[i].id === sisulid) {\r\n");
      out.write("            sisulAllList[i].chk = false;\r\n");
      out.write("            break;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    for (var i = 0; i < selectedSisulList.length; i++) {\r\n");
      out.write("        if (sisulid === selectedSisulList[i].id) {\r\n");
      out.write("            selectedSisulList.splice(i, 1);\r\n");
      out.write("            break;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    setMysisulArea();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 여기까지\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" var calendarData;\r\n");
      out.write("//function setCalendar(){\r\n");
      out.write("//	$(\"#caltbody\").html(\"\");\r\n");
      out.write("//	calendarData = buildCalendar();\r\n");
      out.write("//	$(\".title_month\").text(calendarData.year + \".\" + calendarData.month);\r\n");
      out.write("//	\r\n");
      out.write("//	var valhtml = \"\";\r\n");
      out.write("//	var sun, mon, tue, wed, thu, fri, sat;\r\n");
      out.write("//	for(var i=0; i < calendarData.dayinfo.length; i++){\r\n");
      out.write("//		sun = calendarData.dayinfo[i].sun === undefined ? \"\" : calendarData.dayinfo[i].sun;\r\n");
      out.write("//		mon = calendarData.dayinfo[i].mon === undefined ? \"\" : calendarData.dayinfo[i].mon;\r\n");
      out.write("//		tue = calendarData.dayinfo[i].tue === undefined ? \"\" : calendarData.dayinfo[i].tue;\r\n");
      out.write("//		wed = calendarData.dayinfo[i].wed === undefined ? \"\" : calendarData.dayinfo[i].wed;\r\n");
      out.write("//		thu = calendarData.dayinfo[i].thu === undefined ? \"\" : calendarData.dayinfo[i].thu;\r\n");
      out.write("//		fri = calendarData.dayinfo[i].fri === undefined ? \"\" : calendarData.dayinfo[i].fri;\r\n");
      out.write("//		sat = calendarData.dayinfo[i].sat === undefined ? \"\" : calendarData.dayinfo[i].sat;\r\n");
      out.write("//		\r\n");
      out.write("//		valhtml += '<tr>';\r\n");
      out.write("//		valhtml += '	<td class=\"sun\">';\r\n");
      out.write("//		if(sun !== \"\") {\r\n");
      out.write("//			if(holidayData[i].sun !== \"Y\"){\r\n");
      out.write("//				valhtml += '	<a href=\"#juno\" id=\"'+ String(i+1) + \"_sun_\" + sun + '\" onclick=\"selectDay(' + sun + ')\" day=\"' + sun + '\">' + sun + '</a>';\r\n");
      out.write("//			} else {\r\n");
      out.write("//				valhtml += '	<span class=\"closeday\" id=\"'+ String(i+1) + \"_sun_\" + sun + '\" day=\"' + sun + '\">' + sun + '</span>';\r\n");
      out.write("//			}\r\n");
      out.write("//		}				\r\n");
      out.write("//		valhtml += '	</td>';\r\n");
      out.write("//		valhtml += '	<td>';\r\n");
      out.write("//		if(mon !== \"\") {\r\n");
      out.write("//			if(holidayData[i].mon !== \"Y\"){\r\n");
      out.write("//				valhtml += '	<a href=\"#juno\" id=\"'+ String(i+1) + \"_mon_\" + mon + '\" onclick=\"selectDay(' + mon + ')\" day=\"' + mon + '\">' + mon + '</a>';\r\n");
      out.write("//			} else {\r\n");
      out.write("//				valhtml += '	<span class=\"closeday\" id=\"'+ String(i+1) + \"_mon_\" + mon + '\" day=\"' + mon + '\">' + mon + '</span>';\r\n");
      out.write("//			}\r\n");
      out.write("//		}\r\n");
      out.write("//		valhtml += '	</td>';\r\n");
      out.write("//		valhtml += '	<td>';\r\n");
      out.write("//		if(tue !== \"\") {\r\n");
      out.write("//			if(holidayData[i].tue !== \"Y\"){\r\n");
      out.write("//				valhtml += '	<a href=\"#juno\" id=\"'+ String(i+1) + \"_tue_\" + tue + '\" onclick=\"selectDay(' + tue + ')\" day=\"' + tue + '\">' + tue + '</a>';\r\n");
      out.write("//			} else {\r\n");
      out.write("//				valhtml += '	<span class=\"closeday\" id=\"'+ String(i+1) + \"_tue_\" + tue + '\" day=\"' + tue + '\">' + tue + '</span>';\r\n");
      out.write("//			}\r\n");
      out.write("//		}\r\n");
      out.write("//		valhtml += '	</td>';\r\n");
      out.write("//		valhtml += '	<td>';\r\n");
      out.write("//		if(wed !== \"\") {\r\n");
      out.write("//			if(holidayData[i].wed !== \"Y\"){\r\n");
      out.write("//				valhtml += '	<a href=\"#juno\" id=\"'+ String(i+1) + \"_wed_\" + wed + '\" onclick=\"selectDay(' + wed + ')\" day=\"' + wed + '\">' + wed + '</a>';\r\n");
      out.write("//			} else {\r\n");
      out.write("//				valhtml += '	<span class=\"closeday\" id=\"'+ String(i+1) + \"_wed_\" + wed + '\" day=\"' + wed + '\">' + wed + '</span>';\r\n");
      out.write("//			}\r\n");
      out.write("//		}\r\n");
      out.write("//		valhtml += '	</td>';\r\n");
      out.write("//		valhtml += '	<td>';\r\n");
      out.write("//		if(thu !== \"\") {\r\n");
      out.write("//			if(holidayData[i].thu !== \"Y\"){\r\n");
      out.write("//				valhtml += '	<a href=\"#juno\" id=\"'+ String(i+1) + \"_thu_\" + thu + '\" onclick=\"selectDay(' + thu + ')\" day=\"' + thu + '\">' + thu + '</a>';\r\n");
      out.write("//			} else {\r\n");
      out.write("//				valhtml += '	<span class=\"closeday\" id=\"'+ String(i+1) + \"_thu_\" + thu + '\" day=\"' + thu + '\">' + thu + '</span>';\r\n");
      out.write("//			}\r\n");
      out.write("//		}\r\n");
      out.write("//		valhtml += '	</td>';\r\n");
      out.write("//		valhtml += '	<td>';\r\n");
      out.write("//		if(fri !== \"\") {\r\n");
      out.write("//			if(holidayData[i].fri !== \"Y\"){\r\n");
      out.write("//				valhtml += '	<a href=\"#juno\" id=\"'+ String(i+1) + \"_fri_\" + fri + '\" onclick=\"selectDay(' + fri + ')\" day=\"' + fri + '\">' + fri + '</a>';\r\n");
      out.write("//			} else {\r\n");
      out.write("//				valhtml += '	<span class=\"closeday\" id=\"'+ String(i+1) + \"_fri_\" + fri + '\" day=\"' + fri + '\">' + fri + '</span>';\r\n");
      out.write("//			}\r\n");
      out.write("//		}\r\n");
      out.write("//		valhtml += '	</td>';\r\n");
      out.write("//		valhtml += '	<td class=\"sat\">';\r\n");
      out.write("//		if(sat !== \"\") {\r\n");
      out.write("//			if(holidayData[i].sat !== \"Y\"){\r\n");
      out.write("//				valhtml += '	<a href=\"#juno\" id=\"'+ String(i+1) + \"_sat_\" + sat + '\" onclick=\"selectDay(' + sat + ')\" day=\"' + sat + '\">' + sat + '</a>';\r\n");
      out.write("//			} else {\r\n");
      out.write("//				valhtml += '	<span class=\"closeday\" id=\"'+ String(i+1) + \"_sat_\" + sat + '\" day=\"' + sat + '\">' + sat + '</span>';\r\n");
      out.write("//			}\r\n");
      out.write("//		}\r\n");
      out.write("//		valhtml += '	</td>';\r\n");
      out.write("//		valhtml += '</tr>';\r\n");
      out.write("//	}\r\n");
      out.write("//	$(\"#caltbody\").html(valhtml);\r\n");
      out.write("//}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function initRsvTime(reservedTimeList){\r\n");
      out.write("	var cpcode = 80\r\n");
      out.write("	\r\n");
      out.write("	var amTimelineData = []\r\n");
      out.write("	for(var i=0; i<reservedTimeList.length; i++){\r\n");
      out.write("		if(reservedTimeList[i].ampm === \"am\"){\r\n");
      out.write("			amTimelineData.push(reservedTimeList[i]);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var pmTimelineData = []\r\n");
      out.write("	for(var i=0; i<reservedTimeList.length; i++){\r\n");
      out.write("		if(reservedTimeList[i].ampm === \"pm\"){\r\n");
      out.write("			pmTimelineData.push(reservedTimeList[i]);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var timelinehtml = \"\";\r\n");
      out.write("	timelinehtml += '<div class=\"timesec\">';\r\n");
      out.write("	timelinehtml += '	<p class=\"tit\">오전</p>';\r\n");
      out.write("	timelinehtml += '	<ul>';\r\n");
      out.write("	for(var i=0; i<amTimelineData.length; i++){\r\n");
      out.write("		// cpcode === 83 : 여의도IFC몰점 예약 제한 (모든 시간 예약 불가 상태)\r\n");
      out.write("		if(amTimelineData[i].isExist === \"Y\" || cpcode === 83){\r\n");
      out.write("			timelinehtml += '<li><span class=\"disabled\">' + amTimelineData[i].time + '</span></li>';\r\n");
      out.write("		} else {\r\n");
      out.write("			timelinehtml += '<li><a href=\"#juno\" time24=\"' + amTimelineData[i].time24 + '\" ampm=\"am\" time=\"' + amTimelineData[i].time + '\">' + amTimelineData[i].time + '</a></li>';\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	timelinehtml += '	</ul>';\r\n");
      out.write("	timelinehtml += '</div>';\r\n");
      out.write("	timelinehtml += '<div class=\"timesec\">';\r\n");
      out.write("	timelinehtml += '	<div class=\"line\"><span></span></div>';\r\n");
      out.write("	timelinehtml += '	<p class=\"tit\">오후</p>';\r\n");
      out.write("	timelinehtml += '	<ul>';\r\n");
      out.write("	for(var i=0; i<pmTimelineData.length; i++){\r\n");
      out.write("		// cpcode === 83 : 여의도IFC몰점 예약 제한 (모든 시간 예약 불가 상태)\r\n");
      out.write("		if(pmTimelineData[i].isExist === \"Y\" || cpcode === 83){\r\n");
      out.write("			timelinehtml += '<li><span class=\"disabled\">' + pmTimelineData[i].time + '</span></li>';\r\n");
      out.write("		} else {\r\n");
      out.write("			timelinehtml += '<li><a href=\"#juno\" time24=\"' + pmTimelineData[i].time24 + '\" ampm=\"pm\" time=\"' + pmTimelineData[i].time + '\">' + pmTimelineData[i].time + '</a></li>';\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	timelinehtml += '	</ul>';\r\n");
      out.write("	timelinehtml += '</div>';\r\n");
      out.write("	$(\"#timeline\").html(timelinehtml);\r\n");
      out.write("	\r\n");
      out.write("	//시간 선택시 텍스트 보여지기\r\n");
      out.write("	$('.timesec li a').click(function(){\r\n");
      out.write("		var $this = $(this);\r\n");
      out.write("		rtime24 = $(this).attr(\"time24\");\r\n");
      out.write("		rtime = $(this).attr(\"time\");\r\n");
      out.write("		rampm = $(this).attr(\"ampm\");\r\n");
      out.write("		var $thistit = $this.parent().parent().siblings('.tit').text();\r\n");
      out.write("		var $thistxt = $this.text();\r\n");
      out.write("		$('.timeselect, .m_timeselect').html($thistit + ' ' +  $thistxt).addClass('active');\r\n");
      out.write("		$('.timesec li a').removeClass('active');\r\n");
      out.write("		$(this).addClass('active');\r\n");
      out.write("		return false;\r\n");
      out.write("	})\r\n");
      out.write("\r\n");
      out.write("	// 모바일 시간 선택\r\n");
      out.write("	$('.m_timeselect').click(function(){\r\n");
      out.write("		$('.timeline').toggle();\r\n");
      out.write("		$(this).toggleClass('open');\r\n");
      out.write("		return false;\r\n");
      out.write("	});\r\n");
      out.write("	loading.close();	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//var targetday = targetDateInstance.getDate();\r\n");
      out.write("	\r\n");
      out.write("function prevCal(){\r\n");
      out.write("	//prevCalendar();\r\n");
      out.write("	//setCalendar();\r\n");
      out.write("	//var todayInstance = new Date();\r\n");
      out.write("	//if(targetDateInstance.getFullYear() == todayInstance.getFullYear() && targetDateInstance.getMonth() == todayInstance.getMonth()){\r\n");
      out.write("	//	targetday = todayInstance.getDate();\r\n");
      out.write("	//} else {\r\n");
      out.write("	//	targetday = 1;\r\n");
      out.write("	//}\r\n");
      out.write("	//selectDay(targetday);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function nextCal(){\r\n");
      out.write("	//nextCalendar();\r\n");
      out.write("	//setCalendar();\r\n");
      out.write("	//var todayInstance = new Date();\r\n");
      out.write("	//if(targetDateInstance.getFullYear() == todayInstance.getFullYear() && targetDateInstance.getMonth() == todayInstance.getMonth()){\r\n");
      out.write("	//	targetday = todayInstance.getDate();\r\n");
      out.write("	//} else {\r\n");
      out.write("	//	targetday = 1;\r\n");
      out.write("	//}\r\n");
      out.write("	//selectDay(targetday);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function todayCal(){\r\n");
      out.write("	//setCalendar();\r\n");
      out.write("	//selectDay(targetday);\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("function gotoNext() {\r\n");
      out.write("/*     if ($(\"#timeline\").find(\".active\").length == 0) {\r\n");
      out.write("        alert(\"시간을 선택해주세요.\");\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    if (selectedSisulList.length == 0) {\r\n");
      out.write("        alert(\"예약하실 시술을 선택해주세요.\");\r\n");
      out.write("        return;\r\n");
      out.write("    } */\r\n");
      out.write("\r\n");
      out.write("    // 선택된 시술 목록을 서버로 전송\r\n");
      out.write("    const form = $('<form></form>').attr('action', '/reservationConfirm').attr('method', 'post');\r\n");
      out.write("    selectedSisulList.forEach(sisul => {\r\n");
      out.write("        $('<input>').attr('type', 'hidden').attr('name', 'sisulList').attr('value', JSON.stringify(sisul)).appendTo(form);\r\n");
      out.write("    });\r\n");
      out.write("    form.appendTo('body').submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function gotoPre(){\r\n");
      out.write("	location.href = \"designer?branchId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branchInfo.branchId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/reservation/schedule.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("userId");
      // /WEB-INF/views/reservation/schedule.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/reservation/schedule.jsp(6,0) '${sessionScope.id}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.id}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/reservation/schedule.jsp(103,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/reservation/schedule.jsp(103,9) '${currentMonthDays}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${currentMonthDays}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/reservation/schedule.jsp(103,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("day");
      // /WEB-INF/views/reservation/schedule.jsp(103,9) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("										");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("										<td>");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("										");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/reservation/schedule.jsp(105,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index % 7 == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<tr class=\"CalendarCell\">\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/reservation/schedule.jsp(109,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(designerWorkDay, status.index % 7)}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													");
          out.write("\r\n");
          out.write("													<div\r\n");
          out.write("														style=\"margin-bottom: 5px; color: blue; cursor: pointer;\"\r\n");
          out.write("														onclick=\"selectDay('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/reservation/schedule.jsp(117,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not fn:contains(designerWorkDay, status.index % 7)}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<div style=\"margin-bottom: 5px; color: gray;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${day}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<!-- 빈 셀을 그대로 두어 요일 맞춤 -->\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/reservation/schedule.jsp(125,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index % 7 == 6}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											</tr>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/reservation/schedule.jsp(215,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/reservation/schedule.jsp(216,52) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branchInfo.branchId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/reservation/schedule.jsp(217,54) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designerInfo.designerId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/reservation/schedule.jsp(258,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentMonth}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/reservation/schedule.jsp(275,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designerInfo.designerId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }
}
