/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 16:36:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("	class=\" js no-touch csstransforms csstransforms3d csstransitions\"\r\n");
      out.write("	style=\"\">\r\n");
      out.write("<script type=\"text/javascript\" async=\"\"\r\n");
      out.write("	src=\"https://www.google-analytics.com/analytics.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" async=\"\"\r\n");
      out.write("	src=\"https://www.googletagmanager.com/gtag/js?id=G-DBGPMGH101&amp;l=dataLayer&amp;cx=c\"></script>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/junohair.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<meta http-equiv=\"content-language\" content=\"ko\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"canonical\" href=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"robots\" content=\"index,follow\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta name=\"author\" content=\"TheLink\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:title\" content=\"준오헤어\">\r\n");
      out.write("<meta property=\"og:description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"https://www.junohair.com/static_resources/images/junohair_logo.jpg\">\r\n");
      out.write("<meta property=\"og:url\" content=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"naver-site-verification\"\r\n");
      out.write("	content=\"325867716301e23bfeb7a5c336b9dbea78f76ae7\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//wcs.naver.net/wcslog.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("if(!wcs_add) var wcs_add = {};\r\n");
      out.write("wcs_add[\"wa\"] = \"fce44f52888e1\";\r\n");
      out.write("if(window.wcs) {\r\n");
      out.write("wcs_do();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<title>준오헤어</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/reset.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/sub_common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/sub_style2.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/reservation.css?rscVer=0333\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/jquery/1.12.4/jquery.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/viewportchecker.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/modernizr.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/smoothscroll.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/contents.display.none.css?rscVer=0333\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue/2.6.10/vue.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue-the-mask/vue-the-mask.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/babel-polyfill/7.4.4/polyfill.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/axios/0.19.0/axios.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/common_vue.js?rscVer=0333\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header2.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"container\" class=\"reservation_wrap\">\r\n");
      out.write("		<div class=\"sub_visual\">\r\n");
      out.write("			<div class=\"sub_visual_bg\"\r\n");
      out.write("				style=\"background-image: url('https://www.junohair.com/static_resources/images/junohair/sub/reservation/reser_visual.jpg')\"></div>\r\n");
      out.write("			<div class=\"sub_visual_text\">\r\n");
      out.write("				<strong>관리자 화면</strong>\r\n");
      out.write("				<p class=\"sub_visual_sub_text\">\r\n");
      out.write("					<span>JUNO HAIR, 체계적인 관리의 시작</span>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"contents\" style=\"height: 1200px;\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<div class=\"reservation_intro\" style=\"height: 200px;\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"box recomm\">\r\n");
      out.write("						<a href=\"./register2\">\r\n");
      out.write("							<p class=\"tit\">지점 등록</p>\r\n");
      out.write("							<p class=\"desc\">\r\n");
      out.write("								<span>JUNO HAIR 점포를</span> <span>등록합니다. </span>\r\n");
      out.write("							</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"box recomm\">\r\n");
      out.write("						<a href=\"./adminqna\">\r\n");
      out.write("							<p class=\"tit\">문의답변</p>\r\n");
      out.write("							<p class=\"desc\">\r\n");
      out.write("								<span>고객의 목소리를</span> <span>경청합니다. </span>\r\n");
      out.write("							</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"box reser\">\r\n");
      out.write("						<a href=\"./register1\">\r\n");
      out.write("							<p class=\"tit\">디자이너 등록</p>\r\n");
      out.write("							<p class=\"desc\">\r\n");
      out.write("								<span>최고의 미용 전문가를</span> <span>선별합니다</span>\r\n");
      out.write("							</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"box reser\">\r\n");
      out.write("						<a href=\"./designerall\">\r\n");
      out.write("							<p class=\"tit\">디자이너 조회·삭제</p>\r\n");
      out.write("							<p class=\"desc\">\r\n");
      out.write("								<span>최고의 미용 전문가를</span> <span>확인해보세요</span>\r\n");
      out.write("							</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"box recomm\">\r\n");
      out.write("						<a href=\"./ProductAddTest\">\r\n");
      out.write("							<p class=\"tit\">판매 물품 등록</p>\r\n");
      out.write("							<p class=\"desc\">\r\n");
      out.write("								<span>고객님의 헤어를 책임지는</span> <span>제품을 등록합니다. </span>\r\n");
      out.write("							</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"box reser\">\r\n");
      out.write("						<a href=\"./orderListCheck\">\r\n");
      out.write("							<p class=\"tit\">결제내역조회</p>\r\n");
      out.write("							<p class=\"desc\">\r\n");
      out.write("								<span>고객의 결제내역</span> <span>확인하기</span>\r\n");
      out.write("							</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"box reser\">\r\n");
      out.write("						<a href=\"./reservationListCheck\">\r\n");
      out.write("							<p class=\"tit\">예약내역조회</p>\r\n");
      out.write("							<p class=\"desc\">\r\n");
      out.write("								<span>고객님들의 시술예약</span> <span>확인하기</span>\r\n");
      out.write("							</p>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"intro_noti\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<div class=\"footgotop\" id=\"goTop\">\r\n");
      out.write("			<a href=\"#juno\" onclick=\"goTopbtn()\"><span class=\"blind\">상단으로\r\n");
      out.write("					가기</span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_top\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<div class=\"ft_left\">\r\n");
      out.write("					<div class=\"family_site\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/family_site.png\"\r\n");
      out.write("							alt=\"family site\"> <span class=\"bar\"></span>\r\n");
      out.write("						<ul class=\"fs_list\">\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoHair.png\"\r\n");
      out.write("									alt=\"JUNO HAIR\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoAcademy.png\"\r\n");
      out.write("									alt=\"JUNO ACADEMY\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoAvenue.png\"\r\n");
      out.write("									alt=\"JUNO AVENUE\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='https://www.triamilia.com/'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_triamilia.png\"\r\n");
      out.write("									alt=\"triamilia\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"terms\">\r\n");
      out.write("						<ul class=\"term_list\">\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('/myjuno/privacypolicy?section=1', '_blank');\">이용약관</a></li>\r\n");
      out.write("							<li><span class=\"bar\"></span></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('/myjuno/privacypolicy?section=2', '_blank');\">개인정보처리방침</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"ft_right\">\r\n");
      out.write("					<div class=\"ft_rightTop\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='/junohair/communication/partnership'\">제휴문의</a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">인재채용</a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='/junohair/communication/qna'\">Q&amp;A</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"fr_rightBottom\">\r\n");
      out.write("						<strong><img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/junohair/footer_media_img.png\"\r\n");
      out.write("							alt=\"JUNO SOCIAL MEDIA\"><span class=\"bar\"></span></strong>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.facebook.com/junohair.official/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social1.jpg\"\r\n");
      out.write("									alt=\"facebook\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.instagram.com/junohair_official/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social2.jpg\"\r\n");
      out.write("									alt=\"instagram\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.youtube.com/channel/UCwmPMC_aCMskDKR6P30pn6Q/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social_youtube.jpg\"\r\n");
      out.write("									alt=\"youtube\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_btm\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<strong><img\r\n");
      out.write("					src=\"https://www.junohair.com/static_resources/images/junohair/footer_junohair_logo.png\"\r\n");
      out.write("					alt=\"JUNO HAIR\"></strong>\r\n");
      out.write("				<div class=\"address\">\r\n");
      out.write("					<p>\r\n");
      out.write("						<span>(주)준오뷰티</span> <span>대표자 강윤선</span> <span>서울특별시 강남구\r\n");
      out.write("							청담동 63-14 JUNO &amp; BEAUTY 5층</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span>사업자등록번호 : 110-81-60003</span> <span>통신판매번호 :\r\n");
      out.write("							2020-서울강남-02683호</span> <span>대표전화 +82-2-548-0605</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>Copyright ⓒ 2017 JUNOHAIR.COM. All rights Reserved.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"emblem\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/K_BPI_2020.png\"\r\n");
      out.write("						alt=\"2020 K-BPI 파워엠블렘\" style=\"height: 44px\">\r\n");
      out.write("					<!-- 2020-04-02 이미지경로 수정-->\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/naward.png\"\r\n");
      out.write("						alt=\"2017 &amp;Award\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("	function startReservation(){\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write(" 		if(\"CUST\" != \"CUST\"){\r\n");
      out.write("			alert(\"로그인 후 이용이 가능합니다.\");\r\n");
      out.write("			return\r\n");
      out.write("		}\r\n");
      out.write("		location.href=\"/junohair/reservation/process01_branch\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function startRsvRecmnd(){\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		if(\"CUST\" != \"CUST\"){\r\n");
      out.write("			alert(\"로그인 후 이용이 가능합니다.\");\r\n");
      out.write("			return\r\n");
      out.write("		}\r\n");
      out.write("		location.href=\"/junohair/reservation/ai_process01_info\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
