/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 03:27:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class designer_005fall_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("	class=\" js no-touch csstransforms csstransforms3d csstransitions\"\r\n");
      out.write("	style=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/junohair.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<meta http-equiv=\"content-language\" content=\"ko\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"canonical\" href=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"robots\" content=\"index,follow\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta name=\"author\" content=\"TheLink\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:title\" content=\"준오헤어\">\r\n");
      out.write("<meta property=\"og:description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"https://www.junohair.com/static_resources/images/junohair_logo.jpg\">\r\n");
      out.write("<meta property=\"og:url\" content=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"naver-site-verification\"\r\n");
      out.write("	content=\"325867716301e23bfeb7a5c336b9dbea78f76ae7\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"//wcs.naver.net/wcslog.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	if (!wcs_add)\r\n");
      out.write("		var wcs_add = {};\r\n");
      out.write("	wcs_add[\"wa\"] = \"fce44f52888e1\";\r\n");
      out.write("	if (window.wcs) {\r\n");
      out.write("		wcs_do();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<title>준오헤어</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/reset.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/sub_common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/myjuno/join.css?rscVer=0333\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/jquery/1.12.4/jquery.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/imagesloaded.3.2.x.pkgd.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/isotope.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/modernizr.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/smoothscroll.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/viewportchecker.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/contents.display.none.css?rscVer=0333\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue/2.6.10/vue.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue-the-mask/vue-the-mask.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/babel-polyfill/7.4.4/polyfill.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/axios/0.19.0/axios.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/common_vue.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/myjuno/juno_sub_ui.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/join_css.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./resources/verify.js\"\r\n");
      out.write("	charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header2.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"join\">\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			function gotoMyjuno() {\r\n");
      out.write("				if (\"\" != \"CUST\") {\r\n");
      out.write("					alert(\"로그인후 이용이 가능합니다.\");\r\n");
      out.write("				}\r\n");
      out.write("				location.href = \"/myjuno/member_info\";\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("			<div class=\"sub_visual\">\r\n");
      out.write("				<div class=\"sub_visual_bg\"\r\n");
      out.write("					style=\"background-image: url('https://www.junohair.com/static_resources/images/myjuno/intro_visual.jpg')\"></div>\r\n");
      out.write("				<div class=\"sub_visual_text\">디자이너 조회</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"sub_menu\"></div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 	<div id=\"contents\">\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"inner\"> -->\r\n");
      out.write("			<div class=\"section1\">\r\n");
      out.write("				<div class=\"section_tit\">\r\n");
      out.write("					<span class=\"bar\"></span> <strong class=\"tit\">디자이너 조회</strong>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</br> </br>\r\n");
      out.write("\r\n");
      out.write("			<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif !important;\r\n");
      out.write("	margin: 20px !important;\r\n");
      out.write("	background-color: #f0f2f5 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents {\r\n");
      out.write("	margin-bottom: 200px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board_list {\r\n");
      out.write("	width: 90% !important;\r\n");
      out.write("	margin: 0 auto !important;\r\n");
      out.write("	background-color: #fff !important;\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1) !important;\r\n");
      out.write("	border-radius: 8px !important;\r\n");
      out.write("	overflow: hidden !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table {\r\n");
      out.write("	width: 100% !important;\r\n");
      out.write("	border-collapse: collapse !important;\r\n");
      out.write("	display: table !important;\r\n");
      out.write("	margin: 20px 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thead {\r\n");
      out.write("	background-color: #343a40 !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	text-align: left !important;\r\n");
      out.write("	font-weight: bold !important;\r\n");
      out.write("	display: table-row !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".th, .td {\r\n");
      out.write("	padding: 12px 15px !important;\r\n");
      out.write("	border-bottom: 1px solid #dee2e6 !important;\r\n");
      out.write("	display: table-cell !important;\r\n");
      out.write("	text-align: center !important; /* 가운데 정렬 */\r\n");
      out.write("	vertical-align: middle !important; /* 세로 가운데 정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".th {\r\n");
      out.write("	text-align: center !important;\r\n");
      out.write("	background-color: #6c757d !important;\r\n");
      out.write("	color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".td {\r\n");
      out.write("	text-align: left !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tr {\r\n");
      out.write("	display: table-row !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tr:nth-child(even) {\r\n");
      out.write("	background-color: #f8f9fa !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tr:hover {\r\n");
      out.write("	background-color: #e9ecef !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".noPost {\r\n");
      out.write("	text-align: center !important;\r\n");
      out.write("	font-size: 16px !important;\r\n");
      out.write("	color: #999 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".consult-title {\r\n");
      out.write("	font-weight: bold !important;\r\n");
      out.write("	color: #333 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("	max-width: 100px !important;\r\n");
      out.write("	height: auto !important;\r\n");
      out.write("	border-radius: 8px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	text-decoration: underline !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-delete {\r\n");
      out.write("	color: #dc3545 !important;\r\n");
      out.write("	font-weight: bold !important;\r\n");
      out.write("	cursor: pointer !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 관리자 화면 스타일 추가 */\r\n");
      out.write(".table .th {\r\n");
      out.write("	border-right: 1px solid #ced4da !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table .td {\r\n");
      out.write("	border-right: 1px solid #ced4da !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table .td:last-child, .table .th:last-child {\r\n");
      out.write("	border-right: none !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"contents\">\r\n");
      out.write("				<div class=\"board_list\">\r\n");
      out.write("					<div class=\"table\">\r\n");
      out.write("						<div class=\"thead tr\">\r\n");
      out.write("							<div class=\"th\" style=\"width: 130px;\">ID</div>\r\n");
      out.write("							<div class=\"th\" style=\"width: 130px;\">이름</div>\r\n");
      out.write("							<div class=\"th\">자기소개</div>\r\n");
      out.write("							<div class=\"th\">프로필사진</div>\r\n");
      out.write("							<div class=\"th\">지점</div>\r\n");
      out.write("							<div class=\"th\">비고</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 게시물이 없는 경우 처리 -->\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- 게시물이 있는 경우 -->\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</br> </br> </br>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<div class=\"footgotop\" id=\"goTop\">\r\n");
      out.write("			<a href=\"#juno\" onclick=\"goTopbtn()\"><span class=\"blind\">상단으로\r\n");
      out.write("					가기</span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_top\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<div class=\"ft_left\">\r\n");
      out.write("					<div class=\"family_site\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/family_site.png\"\r\n");
      out.write("							alt=\"family site\"> <span class=\"bar\"></span>\r\n");
      out.write("						<ul class=\"fs_list\">\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoHair.png\"\r\n");
      out.write("									alt=\"JUNO HAIR\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoAcademy.png\"\r\n");
      out.write("									alt=\"JUNO ACADEMY\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoAvenue.png\"\r\n");
      out.write("									alt=\"JUNO AVENUE\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='https://www.triamilia.com/'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_triamilia.png\"\r\n");
      out.write("									alt=\"triamilia\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"terms\">\r\n");
      out.write("						<ul class=\"term_list\">\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('/myjuno/privacypolicy?section=1', '_blank');\">이용약관</a></li>\r\n");
      out.write("							<li><span class=\"bar\"></span></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('/myjuno/privacypolicy?section=2', '_blank');\">개인정보처리방침</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"ft_right\">\r\n");
      out.write("					<div class=\"ft_rightTop\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='/junohair/communication/partnership'\">제휴문의</a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">인재채용</a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='/junohair/communication/qna'\">Q&amp;A</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"fr_rightBottom\">\r\n");
      out.write("						<strong><img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/junohair/footer_media_img.png\"\r\n");
      out.write("							alt=\"JUNO SOCIAL MEDIA\"><span class=\"bar\"></span></strong>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.facebook.com/junohair.official/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social1.jpg\"\r\n");
      out.write("									alt=\"facebook\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.instagram.com/junohair_official/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social2.jpg\"\r\n");
      out.write("									alt=\"instagram\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.youtube.com/channel/UCwmPMC_aCMskDKR6P30pn6Q/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social_youtube.jpg\"\r\n");
      out.write("									alt=\"youtube\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_btm\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<strong><img\r\n");
      out.write("					src=\"https://www.junohair.com/static_resources/images/junohair/footer_junohair_logo.png\"\r\n");
      out.write("					alt=\"JUNO HAIR\"></strong>\r\n");
      out.write("				<div class=\"address\">\r\n");
      out.write("					<p>\r\n");
      out.write("						<span>(주)준오뷰티</span> <span>대표자 강윤선</span> <span>서울특별시 강남구\r\n");
      out.write("							청담동 63-14 JUNO &amp; BEAUTY 5층</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span>사업자등록번호 : 110-81-60003</span> <span>통신판매번호 :\r\n");
      out.write("							2020-서울강남-02683호</span> <span>대표전화 +82-2-548-0605</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>Copyright ⓒ 2017 JUNOHAIR.COM. All rights Reserved.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"emblem\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/K_BPI_2020.png\"\r\n");
      out.write("						alt=\"2020 K-BPI 파워엠블렘\" style=\"height: 44px\">\r\n");
      out.write("					<!-- 2020-04-02 이미지경로 수정-->\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/naward.png\"\r\n");
      out.write("						alt=\"2017 &amp;Award\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"idCheckLayer\">\r\n");
      out.write("		<p class=\"ttl\">아이디 중복 체크</p>\r\n");
      out.write("		<div class=\"layer_content\">\r\n");
      out.write("			<div class=\"search_wrap\">\r\n");
      out.write("				<input type=\"text\" name=\"id_val\" maxlength=\"14\"> <a\r\n");
      out.write("					href=\"#juno\" onclick=\"idDplChkLayerPop.goCheck()\">중복확인</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"search_error\">\r\n");
      out.write("				<span></span>은(는) 사용이 불가한 아이디 입니다.\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"search_success\">\r\n");
      out.write("				<p>\r\n");
      out.write("					입력하신 아이디 <span></span>은(는)<br> 사용하실 수 있습니다.\r\n");
      out.write("				</p>\r\n");
      out.write("				<a href=\"#juno\" onclick=\"idDplChkLayerPop.use()\">사용하기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a href=\"#juno\" class=\"btn_close\" onclick=\"idDplChkLayerPop.close()\"><span\r\n");
      out.write("			class=\"blind\">팝업닫기</span></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"overlay1\" onclick=\"idDplChkLayerPop.close()\"></div>\r\n");
      out.write("	<div class=\"overlaycomm\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/admin/designer_all.jsp(246,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty designer_all}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div class=\"tr noPost\">\r\n");
          out.write("								<div class=\"td\" colspan=\"6\">\r\n");
          out.write("									<p>디자이너가 없습니다.</p>\r\n");
          out.write("								</div>\r\n");
          out.write("							</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/designer_all.jsp(255,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("member");
      // /WEB-INF/views/admin/designer_all.jsp(255,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/designer_all.jsp(255,6) '${designer_all}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${designer_all}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<div class=\"tr\">\r\n");
            out.write("								<div class=\"td\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.designerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("								<div class=\"td consult-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.designerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("								<div class=\"td\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.introduce}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("								<div class=\"td\">\r\n");
            out.write("									<img src=\"./resources/productupload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.designerPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("										alt=\"프로필 사진\">\r\n");
            out.write("								</div>\r\n");
            out.write("								<div class=\"td\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.branchName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("								<div class=\"td\">\r\n");
            out.write("									<a href=\"./designer_del?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.designerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("										class=\"btn-delete\">디자이너 삭제</a>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
