/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 01:07:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class designer_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("	class=\" js no-touch csstransforms csstransforms3d csstransitions\"\r\n");
      out.write("	style=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/junohair.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<meta http-equiv=\"content-language\" content=\"ko\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"canonical\" href=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"robots\" content=\"index,follow\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta name=\"author\" content=\"TheLink\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:title\" content=\"준오헤어\">\r\n");
      out.write("<meta property=\"og:description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"https://www.junohair.com/static_resources/images/junohair_logo.jpg\">\r\n");
      out.write("<meta property=\"og:url\" content=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"naver-site-verification\"\r\n");
      out.write("	content=\"325867716301e23bfeb7a5c336b9dbea78f76ae7\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"//wcs.naver.net/wcslog.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	if (!wcs_add)\r\n");
      out.write("		var wcs_add = {};\r\n");
      out.write("	wcs_add[\"wa\"] = \"fce44f52888e1\";\r\n");
      out.write("	if (window.wcs) {\r\n");
      out.write("		wcs_do();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<title>준오헤어</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/reset.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/sub_common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/myjuno/join.css?rscVer=0333\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/jquery/1.12.4/jquery.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/imagesloaded.3.2.x.pkgd.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/isotope.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/modernizr.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/smoothscroll.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/viewportchecker.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/contents.display.none.css?rscVer=0333\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue/2.6.10/vue.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue-the-mask/vue-the-mask.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/babel-polyfill/7.4.4/polyfill.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/axios/0.19.0/axios.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/common_vue.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/myjuno/juno_sub_ui.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/join_css.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./resources/verify.js\"\r\n");
      out.write("	charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header2.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"join\">\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			function gotoMyjuno() {\r\n");
      out.write("				if (\"\" != \"CUST\") {\r\n");
      out.write("					alert(\"로그인후 이용이 가능합니다.\");\r\n");
      out.write("				}\r\n");
      out.write("				location.href = \"/myjuno/member_info\";\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("			<div class=\"sub_visual\">\r\n");
      out.write("				<div class=\"sub_visual_bg\"\r\n");
      out.write("					style=\"background-image: url('https://www.junohair.com/static_resources/images/myjuno/intro_visual.jpg')\"></div>\r\n");
      out.write("				<div class=\"sub_visual_text\">디자이너 등록</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"sub_menu\"></div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 	<div id=\"contents\">\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"inner\"> -->\r\n");
      out.write("			<div class=\"section1\">\r\n");
      out.write("				<div class=\"section_tit\">\r\n");
      out.write("					<span class=\"bar\"></span> <strong class=\"tit\">디자이너 등록</strong>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 		<div class=\"section_content\">\r\n");
      out.write("							<div class=\"sec1_top\">\r\n");
      out.write("								<div class=\"join_form_wrap\"> -->\r\n");
      out.write("\r\n");
      out.write("			<form id=\"join\" action=\"./RegisterManagerAction\"\r\n");
      out.write("				enctype=\"multipart/form-data\" method=post>\r\n");
      out.write("\r\n");
      out.write("				<table>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 기본정보-->\r\n");
      out.write("						<td colspan=\"2\" class=\"subtitle td\">기본 정보</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 아이디 -->\r\n");
      out.write("						<td class=\"division\">아이디:</td>\r\n");
      out.write("						<td class=\"valuefield\"><input type=\"text\" id=\"ID\" name=\"id\"\r\n");
      out.write("							size=\"12\" maxlength=\"12\"> &nbsp; 4~12자의 영문 대소문자와 숫자로만 입력</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 비밀번호 -->\r\n");
      out.write("						<td class=\"division\">비밀번호:</td>\r\n");
      out.write("						<td class=\"valuefield\"><input type=\"password\" id=\"PW\"\r\n");
      out.write("							name=\"pw\" size=\"12\" maxlength=\"12\"> &nbsp; 4~12자의 영문\r\n");
      out.write("							대소문자와 숫자로만 입력</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 비밀번호 확인 -->\r\n");
      out.write("						<td class=\"division\">비밀번호 확인:</td>\r\n");
      out.write("						<td class=\"valuefield\"><input type=\"password\" id=\"PWconfirm\"\r\n");
      out.write("							name=\"pwconfirm\" size=\"12\" maxlength=\"12\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 메일주소 -->\r\n");
      out.write("						<td class=\"division\">메일주소:</td>\r\n");
      out.write("						<td class=\"valuefield\"><input type=\"text\" id=\"Email\"\r\n");
      out.write("							name=\"email\" size=\"30\"></input> &nbsp; 예) id@domain.com</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 이름 -->\r\n");
      out.write("						<td class=\"division\">이름:</td>\r\n");
      out.write("						<td class=\"valuefield\"><input type=\"text\" id=\"Name\"\r\n");
      out.write("							name=\"name\" size=\"30\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 기본정보-->\r\n");
      out.write("						<td colspan=\"7\" class=\"subtitle\">개인 신상 정보</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 생일 -->\r\n");
      out.write("						<td class=\"division\">생일:</td>\r\n");
      out.write("						<td class=\"valuefield\"><input type=\"text\" id=\"Year\"\r\n");
      out.write("							name=\"year\" size=\"4\" maxlength=\"4\"> 년 <select id=\"Month\"\r\n");
      out.write("							name=\"month\">\r\n");
      out.write("								<option value=\"01\">1</option>\r\n");
      out.write("								<option value=\"02\">2</option>\r\n");
      out.write("								<option value=\"03\">3</option>\r\n");
      out.write("								<option value=\"04\">4</option>\r\n");
      out.write("								<option value=\"05\">5</option>\r\n");
      out.write("								<option value=\"06\">6</option>\r\n");
      out.write("								<option value=\"07\">7</option>\r\n");
      out.write("								<option value=\"08\">8</option>\r\n");
      out.write("								<option value=\"09\">9</option>\r\n");
      out.write("								<option value=\"10\">10</option>\r\n");
      out.write("								<option value=\"11\">11</option>\r\n");
      out.write("								<option value=\"12\">12</option>\r\n");
      out.write("						</select> 월 <select id=\"Day\" name=\"day\">\r\n");
      out.write("								<option value=\"01\">1</option>\r\n");
      out.write("								<option value=\"02\">2</option>\r\n");
      out.write("								<option value=\"03\">3</option>\r\n");
      out.write("								<option value=\"04\">4</option>\r\n");
      out.write("								<option value=\"05\">5</option>\r\n");
      out.write("								<option value=\"06\">6</option>\r\n");
      out.write("								<option value=\"07\">7</option>\r\n");
      out.write("								<option value=\"08\">8</option>\r\n");
      out.write("								<option value=\"09\">9</option>\r\n");
      out.write("								<option value=\"10\">10</option>\r\n");
      out.write("								<option value=\"11\">11</option>\r\n");
      out.write("								<option value=\"12\">12</option>\r\n");
      out.write("								<option value=\"13\">13</option>\r\n");
      out.write("								<option value=\"14\">14</option>\r\n");
      out.write("								<option value=\"15\">15</option>\r\n");
      out.write("								<option value=\"16\">16</option>\r\n");
      out.write("								<option value=\"17\">17</option>\r\n");
      out.write("								<option value=\"18\">18</option>\r\n");
      out.write("								<option value=\"19\">19</option>\r\n");
      out.write("								<option value=\"20\">20</option>\r\n");
      out.write("								<option value=\"21\">21</option>\r\n");
      out.write("								<option value=\"22\">22</option>\r\n");
      out.write("								<option value=\"23\">23</option>\r\n");
      out.write("								<option value=\"24\">24</option>\r\n");
      out.write("								<option value=\"25\">25</option>\r\n");
      out.write("								<option value=\"26\">26</option>\r\n");
      out.write("								<option value=\"27\">27</option>\r\n");
      out.write("								<option value=\"28\">28</option>\r\n");
      out.write("								<option value=\"29\">29</option>\r\n");
      out.write("								<option value=\"30\">30</option>\r\n");
      out.write("								<option value=\"31\">31</option>\r\n");
      out.write("						</select> 일</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"division\">지점명:</td>\r\n");
      out.write("						<td class=\"valuefield\"><select id=\"branchName\"\r\n");
      out.write("							name=\"branchName\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</select></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 자기소개  -->\r\n");
      out.write("						<td class=\"division\">자기소개:</td>\r\n");
      out.write("						<td class=\"valuefield\"><textarea id=\"Intro\" name=\"intro\"\r\n");
      out.write("								cols=\"72\" rows=\"10\"></textarea></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 이름 -->\r\n");
      out.write("						<td class=\"division\">프로필 사진:</td>\r\n");
      out.write("						<td class=\"valuefield\"><input type=\"file\" id=\"profile\"\r\n");
      out.write("							name=\"profile\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"form_right\">\r\n");
      out.write("					<input type=\"submit\" class=\"button\" value=\"디자이너 등록\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("			<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif !important;\r\n");
      out.write("	margin: 20px !important;\r\n");
      out.write("	background-color: #f0f2f5 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#join {\r\n");
      out.write("	width: 80% !important;\r\n");
      out.write("	max-width: 800px !important;\r\n");
      out.write("	margin: 20px auto !important;\r\n");
      out.write("	background-color: #fff !important;\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1) !important;\r\n");
      out.write("	border-radius: 8px !important;\r\n");
      out.write("	padding: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	width: 100% !important;\r\n");
      out.write("	border-collapse: collapse !important;\r\n");
      out.write("	margin: 20px 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".subtitle {\r\n");
      out.write("	background-color: #343a40 !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	text-align: left !important;\r\n");
      out.write("	font-weight: bold !important;\r\n");
      out.write("	padding: 10px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".division {\r\n");
      out.write("	background-color: #f8f8f8 !important;\r\n");
      out.write("	width: 30% !important;\r\n");
      out.write("	font-weight: bold !important;\r\n");
      out.write("	padding: 12px 15px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".valuefield {\r\n");
      out.write("	background-color: #fff !important;\r\n");
      out.write("	padding: 12px 15px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"], input[type=\"file\"], select,\r\n");
      out.write("	textarea {\r\n");
      out.write("	width: calc(100% - 20px) !important;\r\n");
      out.write("	padding: 8px 10px !important;\r\n");
      out.write("	border: 1px solid #ccc !important;\r\n");
      out.write("	border-radius: 4px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"]:focus, input[type=\"password\"]:focus, select:focus,\r\n");
      out.write("	textarea:focus {\r\n");
      out.write("	border-color: #343a40 !important;\r\n");
      out.write("	outline: none !important;\r\n");
      out.write("	box-shadow: 0 0 5px rgba(52, 58, 64, 0.5) !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("	resize: vertical !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".valuefield.datefield {\r\n");
      out.write("	display: flex !important;\r\n");
      out.write("	align-items: center !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".valuefield.datefield input[type=\"text\"], .valuefield.datefield select {\r\n");
      out.write("	width: auto !important;\r\n");
      out.write("	margin-right: 10px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".valuefield.datefield select:last-child {\r\n");
      out.write("	margin-right: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form_right {\r\n");
      out.write("	text-align: center !important;\r\n");
      out.write("	padding: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("	background-color: #343a40 !important;\r\n");
      out.write("	color: #fff !important;\r\n");
      out.write("	padding: 10px 20px !important;\r\n");
      out.write("	border: none !important;\r\n");
      out.write("	border-radius: 4px !important;\r\n");
      out.write("	font-size: 16px !important;\r\n");
      out.write("	cursor: pointer !important;\r\n");
      out.write("	transition: background-color 0.3s !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover {\r\n");
      out.write("	background-color: #23272b !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</br> </br> </br>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div> -->\r\n");
      out.write("\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<div class=\"footgotop\" id=\"goTop\">\r\n");
      out.write("			<a href=\"#juno\" onclick=\"goTopbtn()\"><span class=\"blind\">상단으로\r\n");
      out.write("					가기</span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_top\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<div class=\"ft_left\">\r\n");
      out.write("					<div class=\"family_site\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/family_site.png\"\r\n");
      out.write("							alt=\"family site\"> <span class=\"bar\"></span>\r\n");
      out.write("						<ul class=\"fs_list\">\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoHair.png\"\r\n");
      out.write("									alt=\"JUNO HAIR\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoAcademy.png\"\r\n");
      out.write("									alt=\"JUNO ACADEMY\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_junoAvenue.png\"\r\n");
      out.write("									alt=\"JUNO AVENUE\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='https://www.triamilia.com/'\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/family_triamilia.png\"\r\n");
      out.write("									alt=\"triamilia\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"terms\">\r\n");
      out.write("						<ul class=\"term_list\">\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('/myjuno/privacypolicy?section=1', '_blank');\">이용약관</a></li>\r\n");
      out.write("							<li><span class=\"bar\"></span></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('/myjuno/privacypolicy?section=2', '_blank');\">개인정보처리방침</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"ft_right\">\r\n");
      out.write("					<div class=\"ft_rightTop\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='/junohair/communication/partnership'\">제휴문의</a></li>\r\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">인재채용</a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"location.href='/junohair/communication/qna'\">Q&amp;A</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"fr_rightBottom\">\r\n");
      out.write("						<strong><img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/junohair/footer_media_img.png\"\r\n");
      out.write("							alt=\"JUNO SOCIAL MEDIA\"><span class=\"bar\"></span></strong>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.facebook.com/junohair.official/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social1.jpg\"\r\n");
      out.write("									alt=\"facebook\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.instagram.com/junohair_official/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social2.jpg\"\r\n");
      out.write("									alt=\"instagram\"></a></li>\r\n");
      out.write("							<li><a href=\"#juno\"\r\n");
      out.write("								onclick=\"window.open('https://www.youtube.com/channel/UCwmPMC_aCMskDKR6P30pn6Q/', '_blank');\"><img\r\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_social_youtube.jpg\"\r\n");
      out.write("									alt=\"youtube\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_btm\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<strong><img\r\n");
      out.write("					src=\"https://www.junohair.com/static_resources/images/junohair/footer_junohair_logo.png\"\r\n");
      out.write("					alt=\"JUNO HAIR\"></strong>\r\n");
      out.write("				<div class=\"address\">\r\n");
      out.write("					<p>\r\n");
      out.write("						<span>(주)준오뷰티</span> <span>대표자 강윤선</span> <span>서울특별시 강남구\r\n");
      out.write("							청담동 63-14 JUNO &amp; BEAUTY 5층</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span>사업자등록번호 : 110-81-60003</span> <span>통신판매번호 :\r\n");
      out.write("							2020-서울강남-02683호</span> <span>대표전화 +82-2-548-0605</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>Copyright ⓒ 2017 JUNOHAIR.COM. All rights Reserved.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"emblem\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/K_BPI_2020.png\"\r\n");
      out.write("						alt=\"2020 K-BPI 파워엠블렘\" style=\"height: 44px\">\r\n");
      out.write("					<!-- 2020-04-02 이미지경로 수정-->\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/naward.png\"\r\n");
      out.write("						alt=\"2017 &amp;Award\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"idCheckLayer\">\r\n");
      out.write("		<p class=\"ttl\">아이디 중복 체크</p>\r\n");
      out.write("		<div class=\"layer_content\">\r\n");
      out.write("			<div class=\"search_wrap\">\r\n");
      out.write("				<input type=\"text\" name=\"id_val\" maxlength=\"14\"> <a\r\n");
      out.write("					href=\"#juno\" onclick=\"idDplChkLayerPop.goCheck()\">중복확인</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"search_error\">\r\n");
      out.write("				<span></span>은(는) 사용이 불가한 아이디 입니다.\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"search_success\">\r\n");
      out.write("				<p>\r\n");
      out.write("					입력하신 아이디 <span></span>은(는)<br> 사용하실 수 있습니다.\r\n");
      out.write("				</p>\r\n");
      out.write("				<a href=\"#juno\" onclick=\"idDplChkLayerPop.use()\">사용하기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a href=\"#juno\" class=\"btn_close\" onclick=\"idDplChkLayerPop.close()\"><span\r\n");
      out.write("			class=\"blind\">팝업닫기</span></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"overlay1\" onclick=\"idDplChkLayerPop.close()\"></div>\r\n");
      out.write("	<div class=\"overlaycomm\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/designer_register.jsp(236,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("branch");
      // /WEB-INF/views/admin/designer_register.jsp(236,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/designer_register.jsp(236,8) '${branches}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${branches}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${branch}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
