/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 11:07:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Join_005fLogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("	class=\" js no-touch csstransforms csstransforms3d csstransitions\"\r\n");
      out.write("	style=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/junohair.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<meta http-equiv=\"content-language\" content=\"ko\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"canonical\" href=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"robots\" content=\"index,follow\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta name=\"author\" content=\"TheLink\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:title\" content=\"준오헤어\">\r\n");
      out.write("<meta property=\"og:description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"https://www.junohair.com/static_resources/images/junohair_logo.jpg\">\r\n");
      out.write("<meta property=\"og:url\" content=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"naver-site-verification\"\r\n");
      out.write("	content=\"325867716301e23bfeb7a5c336b9dbea78f76ae7\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\">\r\n");
      out.write("\r\n");
      out.write("<!-- Global site tag (gtag.js) - Google Analytics -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://connect.facebook.net/en_US/sdk.js?hash=726cc7837520108e17dacbbf8f4cc324\"\r\n");
      out.write("	async=\"\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script id=\"facebook-jssdk\"\r\n");
      out.write("	src=\"https://connect.facebook.net/en_US/sdk.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" async=\"\"\r\n");
      out.write("	src=\"https://www.google-analytics.com/analytics.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" async=\"\"\r\n");
      out.write("	src=\"https://www.googletagmanager.com/gtag/js?id=G-DBGPMGH101&amp;l=dataLayer&amp;cx=c\"></script>\r\n");
      out.write("<script async=\"\"\r\n");
      out.write("	src=\"https://www.googletagmanager.com/gtag/js?id=UA-150219424-1\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	window.dataLayer = window.dataLayer || [];\r\n");
      out.write("	function gtag() {\r\n");
      out.write("		dataLayer.push(arguments);\r\n");
      out.write("	}\r\n");
      out.write("	gtag('js', new Date());\r\n");
      out.write("\r\n");
      out.write("	gtag('config', 'UA-150219424-1');\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//wcs.naver.net/wcslog.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	window.onload = function() {\r\n");
      out.write("		// 서버에서 전달된 loginCheck 변수를 가져옵니다.\r\n");
      out.write("		var loginCheck = \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("		// loginCheck 변수가 null이 아닌 경우 알럿을 띄웁니다.\r\n");
      out.write("		if (loginCheck) {\r\n");
      out.write("			alert(loginCheck);\r\n");
      out.write("		}\r\n");
      out.write("	};\r\n");
      out.write("</script>\r\n");
      out.write("<title>준오헤어</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/lib/bootstrap/4.3.1/css/bootstrap.min.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/reset.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/sub_common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/myjuno/member.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/myjuno/login.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/contents.display.none.css?rscVer=0333\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/jquery/1.12.4/jquery.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/viewportchecker.js?rscVer=0333\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".submenu {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cursor {\r\n");
      out.write("	cursor: hand;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/modernizr.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/smoothscroll.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/bootstrap/4.3.1/js/bootstrap.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/naveridlogin_js_sdk_2.0.0.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue/2.6.10/vue.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue-the-mask/vue-the-mask.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/babel-polyfill/7.4.4/polyfill.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/axios/0.19.0/axios.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/common.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/common_vue.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/myjuno/juno_sub_ui.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/js-cookie/3.0.0-rc.0/js.cookie.min.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/kakao/kakao.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\"\r\n");
      out.write("	charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header2.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"login\">\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			window.onload = function() {\r\n");
      out.write("				var errorMessage = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("				if (errorMessage) {\r\n");
      out.write("					alert(errorMessage);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			function gotoMyjuno() {\r\n");
      out.write("				if (\"\" != \"CUST\") {\r\n");
      out.write("					alert(\"로그인후 이용이 가능합니다.\");\r\n");
      out.write("				}\r\n");
      out.write("				location.href = \"/myjuno/member_info\";\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"sub_visual\">\r\n");
      out.write("				<div class=\"sub_visual_bg\"\r\n");
      out.write("					style=\"background-image: url(https://www.junohair.com/static_resources/images/myjuno/intro_visual.jpg)\"></div>\r\n");
      out.write("				<div class=\"sub_visual_text\">로그인</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"sub_menu\"></div>\r\n");
      out.write("			<div id=\"contents\">\r\n");
      out.write("				<div class=\"section1\">\r\n");
      out.write("					<div class=\"inner\">\r\n");
      out.write("						<div class=\"section_tit\">\r\n");
      out.write("							<span class=\"bar\"></span> <strong class=\"tit\">로그인</strong> <span\r\n");
      out.write("								class=\"tit_logo\"> <img\r\n");
      out.write("								src=\"https://www.junohair.com/static_resources/images/myjuno/logo_hair_academy.jpg\"\r\n");
      out.write("								alt=\"준오헤어 준오아카데미 로고\">\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"section_content\">\r\n");
      out.write("							<form id=\"loginFrm\" name=\"loginFrm\" action=\"./LoginAction\"\r\n");
      out.write("								method=\"post\">\r\n");
      out.write("								<input type=\"hidden\" name=\"u_mgb1\" value=\"cust\">\r\n");
      out.write("								<div class=\"form_wrap\">\r\n");
      out.write("									<div class=\"form_top\">\r\n");
      out.write("										<div class=\"form_left\">\r\n");
      out.write("											<p>\r\n");
      out.write("												<strong>아이디</strong><input type=\"text\" name=\"id\" id=\"id\">\r\n");
      out.write("											</p>\r\n");
      out.write("											<p>\r\n");
      out.write("												<strong>비밀번호</strong><input type=\"password\" name=\"pw\"\r\n");
      out.write("													id=\"pw\">\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"form_right\">\r\n");
      out.write("											<input type=\"submit\" class=\"button\" value=\"로그인\" />\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<style>\r\n");
      out.write(".login .form_right input {\r\n");
      out.write("	display: block;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background: #ed1c24;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	line-height: 90px;\r\n");
      out.write("	width: 130px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	-moz-border-radius: 5px;\r\n");
      out.write("	-webkit-border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"clear\"></div>\r\n");
      out.write("									<div class=\"form_btm\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											<!-- <li><input type=\"checkbox\" name=\"save_id\" id=\"save_id\">\r\n");
      out.write("												<label for=\"save_id\"> 아이디저장 </label></li> -->\r\n");
      out.write("											<li><a href=\"./Join1\">회원가입</a></li>\r\n");
      out.write("											<!-- <li><a href=\"#juno\" onclick=\"findIdPw()\">아이디/비밀번호찾기</a>\r\n");
      out.write("											</li> -->\r\n");
      out.write("											<!-- <li class=\"non_memberchk\"><a href=\"#juno\"\r\n");
      out.write("												onclick=\"searchNoMemberOrder()\"><span>J MARKET\r\n");
      out.write("														비회원 주문 조회</span></a></li> -->\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"foot_non_memberchk\">\r\n");
      out.write("								<a href=\"#juno\" onclick=\"searchNoMemberOrder()\">J MARKET 비회원\r\n");
      out.write("									주문 조회</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- footer.jsp 내용 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\"\r\n");
      out.write("			role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\"\r\n");
      out.write("			aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"exampleModalCenterTitle\"\r\n");
      out.write("							style=\"font-size: 20px;\"></h5>\r\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\">\r\n");
      out.write("							<span aria-hidden=\"true\">×</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\" style=\"font-size: 17px; line-height: 1.7;\">\r\n");
      out.write("						추가 정보를 입력하여 가입을 완료해주세요.<br> 이후 <span id=\"sns_name\"></span>을(를)\r\n");
      out.write("						이용하여 간편하게 로그인 할 수 있습니다.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("							data-dismiss=\"modal\">취소</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-danger\" onclick=\"join('s')\">간편\r\n");
      out.write("							회원가입하기</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"loading\" style=\"display: none;\">\r\n");
      out.write("			<div class=\"loading_inner\">\r\n");
      out.write("\r\n");
      out.write("				<img\r\n");
      out.write("					src=\"https://www.junohair.com/static_resources/images/gate_img1.png\"\r\n");
      out.write("					alt=\"JUNO HAIR\">\r\n");
      out.write("\r\n");
      out.write("				<p>진행중 입니다..</p>\r\n");
      out.write("				<div class=\"loading_dots\">\r\n");
      out.write("					<span class=\"loading_dot\"></span> <span class=\"loading_dot\"></span>\r\n");
      out.write("					<span class=\"loading_dot\"></span> <span class=\"loading_dot\"></span>\r\n");
      out.write("					<span class=\"loading_dot\"></span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"fb-root\" class=\" fb_reset\">\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"position: absolute; top: -10000px; width: 0px; height: 0px;\">\r\n");
      out.write("				<div></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/Join_Login/Login.jsp(61,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginCheck}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
