/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 02:45:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.communication;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" class=\" js no-touch csstransforms csstransforms3d csstransitions\" style=\"\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<link rel=\"shortcut icon\" href=\"https://www.junohair.com/static_resources/images/junohair.ico\">\n");
      out.write("	<link rel=\"apple-touch-icon\" href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\n");
      out.write("	<link rel=\"apple-touch-icon-precomposed\" href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\n");
      out.write("	<meta http-equiv=\"content-language\" content=\"ko\">\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("	<link rel=\"canonical\" href=\"https://www.junohair.com/junohair\">\n");
      out.write("	<meta name=\"robots\" content=\"index,follow\">\n");
      out.write("	<meta name=\"description\" content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\n");
      out.write("	<meta name=\"author\" content=\"TheLink\">\n");
      out.write("	<meta property=\"og:type\" content=\"website\">\n");
      out.write("	<meta property=\"og:title\" content=\"준오헤어\">\n");
      out.write("	<meta property=\"og:description\" content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\n");
      out.write("	<meta property=\"og:image\" content=\"https://www.junohair.com/static_resources/images/junohair_logo.jpg\">\n");
      out.write("	<meta property=\"og:url\" content=\"https://www.junohair.com/junohair\">\n");
      out.write("	<meta name=\"naver-site-verification\" content=\"325867716301e23bfeb7a5c336b9dbea78f76ae7\">\n");
      out.write("	<meta name=\"viewport\"\n");
      out.write("		content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\n");
      out.write("	<meta http-equiv=\"imagetoolbar\" content=\"no\">\n");
      out.write("\n");
      out.write("	<!-- Global site tag (gtag.js) - Google Analytics -->\n");
      out.write("	<script type=\"text/javascript\" async=\"\" src=\"https://www.google-analytics.com/analytics.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" async=\"\"\n");
      out.write("		src=\"https://www.googletagmanager.com/gtag/js?id=G-DBGPMGH101&amp;l=dataLayer&amp;cx=c\"></script>\n");
      out.write("	<script async=\"\" src=\"https://www.googletagmanager.com/gtag/js?id=UA-150219424-1\"></script>\n");
      out.write("	<script>\n");
      out.write("		window.dataLayer = window.dataLayer || [];\n");
      out.write("		function gtag() { dataLayer.push(arguments); }\n");
      out.write("		gtag('js', new Date());\n");
      out.write("\n");
      out.write("		gtag('config', 'UA-150219424-1');\n");
      out.write("	</script>\n");
      out.write("	<script type=\"text/javascript\" src=\"//wcs.naver.net/wcslog.js\"></script>\n");
      out.write("	<title>준오헤어</title>\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/reset.css?rscVer=0333\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/common.css?rscVer=0333\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/junohair/common.css?rscVer=0333\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/junohair/sub_common.css?rscVer=0333\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/junohair/sub_style4.css?rscVer=0333\">\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/lib/jquery/1.12.4/jquery.min.js?rscVer=0333\"></script>\n");
      out.write("	<style type=\"text/css\">\n");
      out.write("		.submenu {\n");
      out.write("			display: none;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		.cursor {\n");
      out.write("			cursor: hand;\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/js/viewportchecker.js?rscVer=0333\"></script>\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/js/modernizr.js?rscVer=0333\"></script>\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/js/smoothscroll.js?rscVer=0333\"></script>\n");
      out.write("\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/contents.display.none.css?rscVer=0333\">\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/lib/vue/2.6.10/vue.min.js?rscVer=0333\"></script>\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/lib/vue-the-mask/vue-the-mask.js?rscVer=0333\"></script>\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/lib/babel-polyfill/7.4.4/polyfill.min.js?rscVer=0333\"></script>\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/lib/axios/0.19.0/axios.min.js?rscVer=0333\"></script>\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/js/common.js?rscVer=0333\"></script>\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/js/common_vue.js?rscVer=0333\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"https://www.junohair.com/static_resources/js/junohair/juno_sub_ui.js?rscVer=0333\"></script>\n");
      out.write("	<style>\n");
      out.write("	.customer .section_content .sec_btm .table_wrap .btn_group li input {\n");
      out.write("	    display: block;\n");
      out.write("	    color: #fff;\n");
      out.write("	    text-align: center;\n");
      out.write("	    line-height: 40px;\n");
      out.write("	    font-size: 15px;\n");
      out.write("	    font-weight: 600;\n");
      out.write("	    width: 160px;\n");
      out.write("	    border-radius: 5px;\n");
      out.write("	    -moz-border-radius: 5px;\n");
      out.write("	    -webkit-border-radius: 5px;\n");
      out.write("	    margin-left: 5px;\n");
      out.write("	    background: #ed1c24;\n");
      out.write("	}\n");
      out.write("	</style>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("        function validateForm() {\n");
      out.write("            var checkbox = document.getElementById('agree');\n");
      out.write("            if (!checkbox.checked) {\n");
      out.write("                alert(\"개인정보 취급 방침에 동의해야 합니다.\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("        ");
 if (session.getAttribute("qnaOk") != null) { 
      out.write("\n");
      out.write("	        alert('");
      out.print( session.getAttribute("qnaOk") );
      out.write("');\n");
      out.write("	        ");
 session.removeAttribute("qnaOk"); 
      out.write("\n");
      out.write("    	");
 } 
      out.write("\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<div id=\"wrap\" class=\"vue-contents-container\" style=\"display: block;\">\n");
      out.write("		<!-- header.jsp 내용 -->\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header2.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("		<div id=\"container\">\n");
      out.write("			<div class=\"sub_visual\">\n");
      out.write("				<div class=\"sub_visual_bg\"\n");
      out.write("					style=\"background-image: url(&quot;https://www.junohair.com/static_resources/images/junohair/sub/community/intro_visual.jpg&quot;);\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sub_visual_text\"><strong>COMMUNITY</strong>\n");
      out.write("					<p class=\"sub_visual_sub_text\"><span>고객과의 소통을 최우선으로 <br class=\"m\">생각하는 준오헤어는</span><br> <span>다양한 방법으로 고객의 소리를 듣겠습니다</span></p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"sub_menu w33p\">\n");
      out.write("				<div class=\"inner\">\n");
      out.write("					<ul>\n");
      out.write("						<li><strong><a href=\"#juno\" onclick=\"location.href='news_list'\">NEWS</a></strong></li>\n");
      out.write("						<li class=\"cur\"><strong><a href=\"#juno\">Q&amp;A</a></strong></li>\n");
      out.write("						<li><strong><a href=\"#juno\" onclick=\"location.href='partnership'\">제휴문의</a></strong></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clear\"></div>\n");
      out.write("			<div id=\"contents\" class=\"customer\">\n");
      out.write("				<div class=\"section section1\">\n");
      out.write("					<div class=\"inner\">\n");
      out.write("						<div class=\"section_tit\"><span class=\"bar\"></span> <strong class=\"tit\">Q&amp;A</strong></div>\n");
      out.write("						<div class=\"section_content hidden fadeInUp\">\n");
      out.write("							<div class=\"sec_top\"><img src=\"https://www.junohair.com/static_resources/images/junohair/sub/community/community_top_bg2.png\" alt=\"\">\n");
      out.write("								<p>준오헤어에 대한 제안, 건의, 문의사항이 있으신 경우 소중한 의견을 남겨주세요.</p><br><br>\n");
      out.write("								<p>의견에 대한 답변은 고객 정보에 기재해주신 이메일로 발송됩니다.</p>\n");
      out.write("							</div>\n");
      out.write("							<form action=\"./sendQna\" method=\"post\" onsubmit=\"return validateForm()\">\n");
      out.write("							<div class=\"sec_btm\">\n");
      out.write("								<div class=\"table_wrap\">\n");
      out.write("									<table>\n");
      out.write("										<caption class=\"hide\">Q&amp;A</caption>\n");
      out.write("										<colgroup>\n");
      out.write("											<col class=\"col1\">\n");
      out.write("											<col class=\"col2\">\n");
      out.write("										</colgroup>\n");
      out.write("										<tbody>\n");
      out.write("											<tr>\n");
      out.write("												<th class=\"mobileHide\" style=\"line-height: 34px; padding-top: 9px;\">\n");
      out.write("													<span>아이디<b class=\"nec\">*</b></span></th>\n");
      out.write("												<td style=\"line-height: 34px; padding-top: 9px;\">\n");
      out.write("													<span><input type=\"text\" id=\"cSubject\" name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></span>\n");
      out.write("												</td>\n");
      out.write("											</tr>\n");
      out.write("											<tr>\n");
      out.write("												<th class=\"mobileHide\" style=\"line-height: 34px; padding-top: 9px;\">\n");
      out.write("													<span>이메일<b class=\"nec\">*</b></span></th>\n");
      out.write("												<td style=\"line-height: 34px; padding-top: 9px;\">\n");
      out.write("													<span><input type=\"text\" id=\"cSubject\" name=\"userEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\n");
      out.write("												</td>\n");
      out.write("											</tr>\n");
      out.write("											<tr>\n");
      out.write("												<th class=\"mobileHide\" style=\"line-height: 34px; padding-top: 9px;\">\n");
      out.write("													<span>제목 <b class=\"nec\">*</b></span></th>\n");
      out.write("												<td style=\"line-height: 34px; padding-top: 9px;\">\n");
      out.write("													<span><input type=\"text\" id=\"cSubject\" name=\"title\" style=\"width: 400px;\"></span>\n");
      out.write("												</td>\n");
      out.write("											</tr>\n");
      out.write("											<tr>\n");
      out.write("												<td colspan=\"2\">\n");
      out.write("													<textarea id=\"cContent\" name=\"content\" placeholder=\"내용을 입력해 주세요\" style=\"height: 150px;\"></textarea>\n");
      out.write("												</td>\n");
      out.write("											</tr>\n");
      out.write("										</tbody>\n");
      out.write("									</table>\n");
      out.write("									<div class=\"agree\">\n");
      out.write("										<div>\n");
      out.write("											<dl>\n");
      out.write("												<dt>개인정보 수집 및 이용에 대한 안내</dt>\n");
      out.write("												<dd>-수집 및 이용 항목 : 성명/연락처/이메일/문의내용</dd>\n");
      out.write("												<dd>-수집 및 이용 목적 : 상담/고객응대/건의해결</dd>\n");
      out.write("												<dd>-수집 및 제공 : 민원처리를 위해 담당자(준오헤어 협력업체:CS Solution)/해당 부서/매장에 내용 및 정보제공\n");
      out.write("												</dd>\n");
      out.write("												<dd>-수집 및 이용 기간 : 처리 후 30일 이내 삭제되며, 그 외 용도로는 사용되지 않습니다.</dd>\n");
      out.write("											</dl>\n");
      out.write("											<p>그 밖의 사항은 개인정보취급방침을 준수 합니다. </p>\n");
      out.write("										</div>\n");
      out.write("										<label for=\"agree\"><input type=\"checkbox\" name=\"agree\" id=\"agree\">\n");
      out.write("											<span>개인정보 취급 방침에 동의 합니다.</span>\n");
      out.write("										</label>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"btn_group\">\n");
      out.write("										<ul>\n");
      out.write("											<li><input type=\"submit\" value=\"상담신청\" class=\"submit\"></li>\n");
      out.write("										</ul>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"footer\">\n");
      out.write("			<div id=\"goTop\" class=\"footgotop\"><a href=\"#juno\" onclick=\"goTopbtn()\"><span class=\"blind\">상단으로\n");
      out.write("						가기</span></a></div>\n");
      out.write("			<div class=\"footer_top\">\n");
      out.write("				<div class=\"inner\">\n");
      out.write("					<div class=\"ft_left\">\n");
      out.write("						<div class=\"family_site\"><img src=\"https://www.junohair.com/static_resources/images/family_site.png\" alt=\"family site\">\n");
      out.write("							<span class=\"bar\"></span>\n");
      out.write("							<ul class=\"fs_list\">\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/junohair'\"><img\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/family_junoHair.png\" alt=\"JUNO HAIR\"></a></li>\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\"><img\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/family_junoAcademy.png\"\n");
      out.write("											alt=\"JUNO ACADEMY\"></a></li>\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\"><img\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/family_junoAvenue.png\" alt=\"JUNO AVENUE\"></a>\n");
      out.write("								</li>\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='https://www.triamilia.com/'\"><img\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/family_triamilia.png\" alt=\"triamilia\"></a>\n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"terms\">\n");
      out.write("							<ul class=\"term_list\">\n");
      out.write("								<li><a href=\"#juno\"\n");
      out.write("										onclick=\"window.open('/myjuno/privacypolicy?section=1', '_blank');\">이용약관</a>\n");
      out.write("								</li>\n");
      out.write("								<li><span class=\"bar\"></span></li>\n");
      out.write("								<li><a href=\"#juno\"\n");
      out.write("										onclick=\"window.open('/myjuno/privacypolicy?section=2', '_blank');\">개인정보처리방침</a>\n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"ft_right\">\n");
      out.write("						<div class=\"ft_rightTop\">\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"#juno\"\n");
      out.write("										onclick=\"location.href='/junohair/communication/partnership'\">제휴문의</a></li>\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">인재채용</a></li>\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/junohair/communication/qna'\">Q&amp;A</a>\n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"fr_rightBottom\"><strong><img\n");
      out.write("									src=\"https://www.junohair.com/static_resources/images/junohair/footer_media_img.png\"\n");
      out.write("									alt=\"JUNO SOCIAL MEDIA\"><span class=\"bar\"></span></strong>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"#juno\"\n");
      out.write("										onclick=\"window.open('https://www.facebook.com/junohair.official/', '_blank');\"><img\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/junohair/footer_social1.jpg\"\n");
      out.write("											alt=\"facebook\"></a></li>\n");
      out.write("								<li><a href=\"#juno\"\n");
      out.write("										onclick=\"window.open('https://www.instagram.com/junohair_official/', '_blank');\"><img\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/junohair/footer_social2.jpg\"\n");
      out.write("											alt=\"instagram\"></a></li>\n");
      out.write("								<li><a href=\"#juno\"\n");
      out.write("										onclick=\"window.open('https://www.youtube.com/channel/UCwmPMC_aCMskDKR6P30pn6Q/', '_blank');\"><img\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/junohair/footer_social_youtube.jpg\"\n");
      out.write("											alt=\"youtube\"></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"footer_btm\">\n");
      out.write("				<div class=\"inner\"><strong><img src=\"https://www.junohair.com/static_resources/images/junohair/footer_junohair_logo.png\"\n");
      out.write("							alt=\"JUNO HAIR\"></strong>\n");
      out.write("					<div class=\"address\">\n");
      out.write("						<p><span>(주)준오뷰티</span> <span>대표자 강윤선</span> <span>서울특별시 강남구 청담동 63-14 JUNO &amp; BEAUTY\n");
      out.write("								5층</span></p>\n");
      out.write("						<p><span>사업자등록번호 : 110-81-60003</span> <span>통신판매번호 : 2020-서울강남-02683호</span> <span>대표전화\n");
      out.write("								+82-2-548-0605</span></p>\n");
      out.write("						<p>Copyright ⓒ 2017 JUNOHAIR.COM. All rights Reserved.</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"emblem\"><img src=\"https://www.junohair.com/static_resources/images/K_BPI_2020.png\" alt=\"2020 K-BPI 파워엠블렘\"\n");
      out.write("							style=\"height: 44px;\"> <img src=\"https://www.junohair.com/static_resources/images/naward.png\" alt=\"2017 &amp;Award\">\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
