/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-04 11:06:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("	class=\" js no-touch csstransforms csstransforms3d csstransitions\"\r\n");
      out.write("	style=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/junohair.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\r\n");
      out.write("<meta http-equiv=\"content-language\" content=\"ko\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"canonical\" href=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"robots\" content=\"index,follow\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta name=\"author\" content=\"TheLink\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:title\" content=\"준오헤어\">\r\n");
      out.write("<meta property=\"og:description\"\r\n");
      out.write("	content=\"헤어&amp;뷰티 업계의 리딩 브랜드, 당신이 아름다워지는 과정을 경험해보세요\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"https://www.junohair.com/static_resources/images/junohair_logo.jpg\">\r\n");
      out.write("<meta property=\"og:url\" content=\"https://www.junohair.com/junohair\">\r\n");
      out.write("<meta name=\"naver-site-verification\"\r\n");
      out.write("	content=\"325867716301e23bfeb7a5c336b9dbea78f76ae7\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi\">\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>준오헤어</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/reset.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/owl.carousel.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/slide_animate.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/common.css?rscVer=0333\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/junohair/main_style.css?rscVer=0333\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://www.junohair.com/static_resources/css/contents.display.none.css?rscVer=0333\">\r\n");
      out.write("\r\n");
      out.write(" <script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/jquery/1.12.4/jquery.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/owl.carousel.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/imagesloaded.3.2.x.pkgd.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/viewportchecker.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/modernizr.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/smoothscroll.js?rscVer=0333\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue/2.6.10/vue.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/vue-the-mask/vue-the-mask.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/babel-polyfill/7.4.4/polyfill.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/axios/0.19.0/axios.min.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/common_vue.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/js/junohair/juno_main_ui.js?rscVer=0333\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://www.junohair.com/static_resources/lib/js-cookie/3.0.0-rc.0/js.cookie.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<!-- header.jsp 내용 -->\r\n");
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header2.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("admin", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			function gotoMyjuno() {\r\n");
      out.write("				if (\"\" != \"CUST\") {\r\n");
      out.write("					alert(\"로그인후 이용이 가능합니다.\");\r\n");
      out.write("				}\r\n");
      out.write("				location.href = \"/myjuno/member_info\";\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"owl-item cloned\"\r\n");
      out.write("				style=\"width: 1903px; margin-right: 0px;\">\r\n");
      out.write("				<div class=\"visual_item\"\r\n");
      out.write("					onclick=\"location='./noticeDetail?id=2'\"\r\n");
      out.write("					style=\"cursor: pointer;\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://www.junohair.com/upload/visual/202406/06abf9b4aefa4dd7a7f954feb2597d08.png\"\r\n");
      out.write("						alt=\"\">\r\n");
      out.write("					<div class=\"visual_bg\"\r\n");
      out.write("						style=\"background-image: url(https://www.junohair.com/upload/visual/202406/89af406befe342cabac5fda9260e48d1.png)\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"contents\">\r\n");
      out.write("				<div class=\"mainbanner\">\r\n");
      out.write("					<div class=\"inner\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"bann01\"><a href=\"branch\">\r\n");
      out.write("									<p class=\"tit\">실시간 예약하기</p>\r\n");
      out.write("									<p class=\"desc\">쉽고 간편한 매장 예약과 디자이너를 추천해 드립니다.</p>\r\n");
      out.write("									<p class=\"img\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/junohair/main/mainbann01.jpg\"\r\n");
      out.write("											alt=\"\">\r\n");
      out.write("									</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li class=\"bann02\"><a href=\"jmarket\">\r\n");
      out.write("									<p class=\"tit\">J MARKET 이용하기</p>\r\n");
      out.write("									<p class=\"desc\">건강한 모발과 두피를 위한 뷰티 제품을 만나보세요.</p>\r\n");
      out.write("									<p class=\"img\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://www.junohair.com/static_resources/images/junohair/main/mainbann02.jpg\"\r\n");
      out.write("											alt=\"\">\r\n");
      out.write("									</p>\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"maininstargram\">\r\n");
      out.write("					<div class=\"inner\">\r\n");
      out.write("						<h2 class=\"title\"># INSTAGRAM</h2>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"tit\">\r\n");
      out.write("							<span>junohair_official</span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"insta_slide insta_offi_slide owl-carousel owl-theme owl-loaded\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"owl-stage-outer\">\r\n");
      out.write("								<div class=\"owl-stage\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<p class=\"tit\">\r\n");
      out.write("							<span>junohair_collection</span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"insta_slide insta_coll_slide owl-carousel owl-theme owl-loaded\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"owl-stage-outer\">\r\n");
      out.write("								<div class=\"owl-stage\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mainyoubube\">\r\n");
      out.write("					<div class=\"inner\">\r\n");
      out.write("						<h2 class=\"title\">JUNO YOUTUBE</h2>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"hidden\"><a href=\"#none\"\r\n");
      out.write("								onclick=\"openPopMovie('azVQDiNl-Qo');return false;\">\r\n");
      out.write("									<div class=\"img\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://www.junohair.com/upload/youtube/202010/35907d8937384d58aef5ad627e271742.jpg\"\r\n");
      out.write("											alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"tbox\">\r\n");
      out.write("										<p>마음이 편안해지는 힐링 영상 / 헤드스파 / JUNOHAIR HEAD SPA</p>\r\n");
      out.write("									</div>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li class=\"hidden\"><a href=\"#none\"\r\n");
      out.write("								onclick=\"openPopMovie('cvW1GoYKHIg');return false;\">\r\n");
      out.write("									<div class=\"img\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://www.junohair.com/upload/youtube/202011/c905f84a776c4218bdccfda6f5920d47.jpg\"\r\n");
      out.write("											alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"tbox\">\r\n");
      out.write("										<p>헤어 디자이너가 알려주는 두피 모발 관리법 / 민감성 두피 / 건조한 모발 / 광고아님 /\r\n");
      out.write("											내돈내산후기</p>\r\n");
      out.write("									</div>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li class=\"hidden\"><a href=\"#none\"\r\n");
      out.write("								onclick=\"openPopMovie('a4k-51JflMs');return false;\">\r\n");
      out.write("									<div class=\"img\">\r\n");
      out.write("										<img\r\n");
      out.write("											src=\"https://www.junohair.com/upload/youtube/202101/d86532d8db5d4f40888f68772f9c8480.jpg\"\r\n");
      out.write("											alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"tbox\">\r\n");
      out.write("										<p>준오가 여러분에게 작은 위로가 되어드릴게요 / 준오헤어 대국민 응원이벤트 / 감동영상 / 힘내라\r\n");
      out.write("											대한민국</p>\r\n");
      out.write("									</div>\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<div class=\"btn_data_more\" id=\"btn_data_more\">\r\n");
      out.write("							<a href=\"#juno\" onclick=\"moreView()\">더보기</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			<div class=\"footgotop\" id=\"goTop\">\r\n");
      out.write("				<a href=\"#juno\" onclick=\"goTopbtn()\"><span class=\"blind\">상단으로\r\n");
      out.write("						가기</span></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footer_top\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<div class=\"ft_left\">\r\n");
      out.write("						<div class=\"family_site\">\r\n");
      out.write("							<img\r\n");
      out.write("								src=\"https://www.junohair.com/static_resources/images/family_site.png\"\r\n");
      out.write("								alt=\"family site\"> <span class=\"bar\"></span>\r\n");
      out.write("							<ul class=\"fs_list\">\r\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/junohair'\"><img\r\n");
      out.write("										src=\"https://www.junohair.com/static_resources/images/family_junoHair.png\"\r\n");
      out.write("										alt=\"JUNO HAIR\"></a></li>\r\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\"><img\r\n");
      out.write("										src=\"https://www.junohair.com/static_resources/images/family_junoAcademy.png\"\r\n");
      out.write("										alt=\"JUNO ACADEMY\"></a></li>\r\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\"><img\r\n");
      out.write("										src=\"https://www.junohair.com/static_resources/images/family_junoAvenue.png\"\r\n");
      out.write("										alt=\"JUNO AVENUE\"></a></li>\r\n");
      out.write("								<li><a href=\"#juno\"\r\n");
      out.write("									onclick=\"location.href='https://www.triamilia.com/'\"><img\r\n");
      out.write("										src=\"https://www.junohair.com/static_resources/images/family_triamilia.png\"\r\n");
      out.write("										alt=\"triamilia\"></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"terms\">\r\n");
      out.write("							<ul class=\"term_list\">\r\n");
      out.write("								<li><a href=\"#juno\"\r\n");
      out.write("									onclick=\"window.open('/myjuno/privacypolicy?section=1', '_blank');\">이용약관</a></li>\r\n");
      out.write("								<li><span class=\"bar\"></span></li>\r\n");
      out.write("								<li><a href=\"#juno\"\r\n");
      out.write("									onclick=\"window.open('/myjuno/privacypolicy?section=2', '_blank');\">개인정보처리방침</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"ft_right\">\r\n");
      out.write("						<div class=\"ft_rightTop\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#juno\"\r\n");
      out.write("									onclick=\"location.href='/junohair/communication/partnership'\">제휴문의</a></li>\r\n");
      out.write("								<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">인재채용</a></li>\r\n");
      out.write("								<li><a href=\"#juno\"\r\n");
      out.write("									onclick=\"location.href='/junohair/communication/qna'\">Q&amp;A</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"fr_rightBottom\">\r\n");
      out.write("							<strong><img\r\n");
      out.write("								src=\"https://www.junohair.com/static_resources/images/junohair/footer_media_img.png\"\r\n");
      out.write("								alt=\"JUNO SOCIAL MEDIA\"><span class=\"bar\"></span></strong>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"\"><img\r\n");
      out.write("										src=\"https://www.junohair.com/static_resources/images/junohair/footer_social1.jpg\"\r\n");
      out.write("										alt=\"facebook\"></a></li>\r\n");
      out.write("								<li><a href=\"\"><img\r\n");
      out.write("										src=\"https://www.junohair.com/static_resources/images/junohair/footer_social2.jpg\"\r\n");
      out.write("										alt=\"instagram\"></a></li>\r\n");
      out.write("								<li><a href=\"#\"><img\r\n");
      out.write("										src=\"https://www.junohair.com/static_resources/images/junohair/footer_social_youtube.jpg\"\r\n");
      out.write("										alt=\"youtube\"></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footer_btm\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<strong><img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/junohair/footer_junohair_logo.png\"\r\n");
      out.write("						alt=\"JUNO HAIR\"></strong>\r\n");
      out.write("					<div class=\"address\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<span>(주)준오뷰티</span> <span>대표자 강윤선</span> <span>서울특별시 강남구\r\n");
      out.write("								청담동 63-14 JUNO &amp; BEAUTY 5층</span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<span>사업자등록번호 : 110-81-60003</span> <span>통신판매번호 :\r\n");
      out.write("								2020-서울강남-02683호</span> <span>대표전화 +82-2-548-0605</span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>Copyright ⓒ 2017 JUNOHAIR.COM. All rights Reserved.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"emblem\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/K_BPI_2020.png\"\r\n");
      out.write("							alt=\"2020 K-BPI 파워엠블렘\" style=\"height: 44px\">\r\n");
      out.write("						<!-- 2020-04-02 이미지경로 수정-->\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://www.junohair.com/static_resources/images/naward.png\"\r\n");
      out.write("							alt=\"2017 &amp;Award\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 인스타그램 popup  -->\r\n");
      out.write("	<div class=\"popupInstagram\">\r\n");
      out.write("		<div class=\"instagram_post\">\r\n");
      out.write("			<div class=\"media\" id=\"instamedia\">\r\n");
      out.write("				<img\r\n");
      out.write("					src=\"https://www.junohair.com/static_resources/images/junohair/main/@instagram_media.jpg\"\r\n");
      out.write("					alt=\"\" id=\"instapopimg\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"cont\">\r\n");
      out.write("				<div class=\"top\">\r\n");
      out.write("					<span class=\"profileimg\"><img\r\n");
      out.write("						src=\"https://www.junohair.com/static_resources/images/junohair/main/@instagram_profile.png\"\r\n");
      out.write("						alt=\"\"></span> <span class=\"ttl\" id=\"instapopttl\">junohair_officaial</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tbox\" id=\"tbox\">\r\n");
      out.write("					JUNO HAIR <br> Avenue JUNO <br> 건축.인테리어디자인 분야에서 권위있는 <br>\r\n");
      out.write("					네덜란드 잡지 FRAME에 애브뉴준오가 <br> 소개되었습니다. 준오는 고객분들과 <br> 디자이너에게\r\n");
      out.write("					영감을 줄 수 있는 공간을 <br> 만들기 위해 더욱 노력하겠습니다.<br> Avenue Juno\r\n");
      out.write("					was published in the <br> Dutch magazine FRAME, the world's <br>\r\n");
      out.write("					leading interior design publication. <br> Juno strives to\r\n");
      out.write("					create a space to <br> inspire customers and designers.<br>\r\n");
      out.write("					- 준오헤어 헤어리뷰 인스타그램 : <br> @junohair_collection<br> 준오헤어 공식\r\n");
      out.write("					유튜브 : junohair official<br> 준오아카데미 : @junoacademy<br> .\r\n");
      out.write("					#준오헤어 #junohair #juno #준오 <br> #junosalon #beautysalon\r\n");
      out.write("					#준오프로페셔널 <br> #salon #interiors #spatialdesign <br>\r\n");
      out.write("					#southkorea #kbeauty #kbeautysalon <br> #koreasalon #hairsalon\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a href=\"#none\" class=\"btnClose\"\r\n");
      out.write("			onclick=\"closePopInstagram();return false;\"><span class=\"blind\">닫기</span></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //인스타그램 popup  -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 유투브 popup  -->\r\n");
      out.write("	<div class=\"popupMovie\">\r\n");
      out.write("		<div class=\"bgcover\">\r\n");
      out.write("			<div class=\"movie\"></div>\r\n");
      out.write("			<img\r\n");
      out.write("				src=\"https://www.junohair.com/static_resources/images/junohair/main/bg_moviesize.gif\"\r\n");
      out.write("				alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<a href=\"#none\" class=\"btnClose\"\r\n");
      out.write("			onclick=\"closePopMovie();return false;\"><span class=\"blind\">닫기</span></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //유투브 popup  -->\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		var officialJson = []\r\n");
      out.write("\r\n");
      out.write("		var colletionJson = []\r\n");
      out.write("\r\n");
      out.write("		function openPopInsta(index, target) {\r\n");
      out.write("			var idx = Number(index);\r\n");
      out.write("			var mediaType;\r\n");
      out.write("			var imghtml;\r\n");
      out.write("			var instaDataJson;\r\n");
      out.write("			if (target == \"official\") {\r\n");
      out.write("				instaDataJson = officialJson;\r\n");
      out.write("				$(\"#instapopttl\").text(\"junohair_officaial\");\r\n");
      out.write("				mediaType = instaDataJson[idx].mediaType;\r\n");
      out.write("			} else if (target == \"collection\") {\r\n");
      out.write("				instaDataJson = colletionJson;\r\n");
      out.write("				$(\"#instapopttl\").text(\"junohair_collection\");\r\n");
      out.write("				mediaType = instaDataJson[idx].mediaType;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			mediaType = instaDataJson[idx].mediaType;\r\n");
      out.write("			if (mediaType == \"VIDEO\") {\r\n");
      out.write("				imghtml = '<img src=\"'+ instaDataJson[idx].thumbnailUrl +'\" alt=\"\" id=\"instapopimg\" />';\r\n");
      out.write("				$(\"#instamedia\").html(imghtml);\r\n");
      out.write("				$(\"#tbox\").html(\r\n");
      out.write("						(instaDataJson[idx].caption).replaceAll(\"\\n\", \"<br/>\"));\r\n");
      out.write("				openPopInstagram();\r\n");
      out.write("			} else {\r\n");
      out.write("				imghtml = '<img src=\"'+ instaDataJson[idx].mediaUrl +'\" alt=\"\" id=\"instapopimg\"/>';\r\n");
      out.write("				$(\"#instamedia\").html(imghtml);\r\n");
      out.write("				$(\"#tbox\").html(\r\n");
      out.write("						(instaDataJson[idx].caption).replaceAll(\"\\n\", \"<br/>\"));\r\n");
      out.write("				openPopInstagram();\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		var youtubeoffset = 0\r\n");
      out.write("		var toutubecount = 3;\r\n");
      out.write("\r\n");
      out.write("		function goSearchYoutube() {\r\n");
      out.write("			var params = {\r\n");
      out.write("				offset : youtubeoffset,\r\n");
      out.write("				count : toutubecount,\r\n");
      out.write("			}\r\n");
      out.write("			cf_call(\"/junohair/getYoutubeList\", params, goSearchYoutubeCB);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function goSearchYoutubeCB(data) {\r\n");
      out.write("			if (data.errMsg != undefined) {\r\n");
      out.write("				alert(data.errMsg);\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			var dataList = data.list;\r\n");
      out.write("\r\n");
      out.write("			var mainyoubube_html = \"\";\r\n");
      out.write("			for (var i = 0; i < dataList.length; i++) {\r\n");
      out.write("\r\n");
      out.write("				mainyoubube_html += '<li>';\r\n");
      out.write("				mainyoubube_html += '	<a href=\"#none\" onclick=\"openPopMovie(\\''\r\n");
      out.write("						+ dataList[i].linkParam + '\\');return false;\">';\r\n");
      out.write("				mainyoubube_html += '		<div class=\"img\"><img src=\"' + dataList[i].file1 + '\" alt=\"\"></div>';\r\n");
      out.write("				mainyoubube_html += '		<div class=\"tbox\">';\r\n");
      out.write("				mainyoubube_html += '			<p>' + dataList[i].yDesc + '</p>';\r\n");
      out.write("				mainyoubube_html += '		</div>';\r\n");
      out.write("				mainyoubube_html += '	</a>';\r\n");
      out.write("				mainyoubube_html += '</li>';\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			$('.mainyoubube ul').append(mainyoubube_html).promise().done(\r\n");
      out.write("					function() {\r\n");
      out.write("						$('.mainyoubube li').addClass(\"hidden\")\r\n");
      out.write("								.viewportChecker({\r\n");
      out.write("									classToAdd : 'zoomIn',\r\n");
      out.write("									offset : 80\r\n");
      out.write("								});\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("			if (youtubeoffset + 3 >= data.totCount) {\r\n");
      out.write("				$(\"#btn_data_more\").hide();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function moreView() {\r\n");
      out.write("			youtubeoffset += toutubecount;\r\n");
      out.write("			goSearchYoutube();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function gotoReservation() {\r\n");
      out.write("			location.href = \"/junohair/reservation/intro\";\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function gotoJMarket() {\r\n");
      out.write("			location.href = \"/junohair/jmarket/prodlist\";\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function openPopInstaMovie(mediaUrl) {\r\n");
      out.write("			$('.popupMovie').show();\r\n");
      out.write("			var _mvaddress;\r\n");
      out.write("			var _mv = '<iframe src=\"'\r\n");
      out.write("					+ mediaUrl\r\n");
      out.write("					+ '\" width=\"100%\" height=\"100%\" allow=\"autoplay; encrypted-media\"></iframe>';\r\n");
      out.write("\r\n");
      out.write("			$('.popupMovie .movie').append(_mv);\r\n");
      out.write("			$('body')\r\n");
      out.write("					.append(\r\n");
      out.write("							'<div id=\"bgDimm\" class=\"bg_dimm\" onclick=\"closePopMovie();return false;\"></div>')\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		$(function() {\r\n");
      out.write("			goSearchYoutube();\r\n");
      out.write("\r\n");
      out.write("			var hairPopTodayYn = Cookies.get('hairPopTodayYn');\r\n");
      out.write("\r\n");
      out.write("			if (hairPopTodayYn !== \"N\" && 1 > 0) {\r\n");
      out.write("				$(\"#popupMainRolling\").show();\r\n");
      out.write("				$(\"#bg_dimm_rolling\").show();\r\n");
      out.write("\r\n");
      out.write("				//메인 롤링 popup\r\n");
      out.write("				var rollingimg_len = $('#popupMainRolling .rolling_img a').length;\r\n");
      out.write("				$('#popupMainRolling .rolling_img').owlCarousel({\r\n");
      out.write("					dots : (rollingimg_len > 1) ? true : false,\r\n");
      out.write("					loop : (rollingimg_len > 1) ? true : false,\r\n");
      out.write("					nav : false,\r\n");
      out.write("					items : 1,\r\n");
      out.write("					touchDrag : true,\r\n");
      out.write("					autoplay : true,\r\n");
      out.write("					smartSpeed : 700\r\n");
      out.write("				})\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\"#popupMainRolling\").hide();\r\n");
      out.write("				$(\"#bg_dimm_rolling\").hide();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function todayCloseNewPop() {\r\n");
      out.write("			$('#popupMainRolling').hide();\r\n");
      out.write("			$('#bg_dimm_rolling').hide();\r\n");
      out.write("			Cookies.set('hairPopTodayYn', 'N', {\r\n");
      out.write("				expires : 1\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function closeNewPop() {\r\n");
      out.write("			$('#popupMainRolling').hide();\r\n");
      out.write("			$('#bg_dimm_rolling').hide();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
