/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-07-03 08:50:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.market;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SJ/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Juno/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716879715354L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" class=\" js no-touch csstransforms csstransforms3d csstransitions\" style=\"\"><head>\n");
      out.write("\n");
      out.write("<link rel=\"shortcut icon\" href=\"https://www.junohair.com/static_resources/images/junohair.ico\">\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"https://www.junohair.com/static_resources/images/apple-touch-icon.png\">\n");
      out.write("<link rel=\"canonical\" href=\"https://www.junohair.com/junohair\">\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Global site tag (gtag.js) - Google Analytics -->\n");
      out.write("<script type=\"text/javascript\" async=\"\" src=\"https://www.google-analytics.com/analytics.js\"></script>\n");
      out.write("<script type=\"text/javascript\" async=\"\" src=\"https://www.googletagmanager.com/gtag/js?id=G-DBGPMGH101&amp;l=dataLayer&amp;cx=c\"></script>\n");
      out.write("<script async=\"\" src=\"https://www.googletagmanager.com/gtag/js?id=UA-150219424-1\"></script>\n");
      out.write("<script>\n");
      out.write("  window.dataLayer = window.dataLayer || [];\n");
      out.write("  function gtag(){dataLayer.push(arguments);}\n");
      out.write("  gtag('js', new Date());\n");
      out.write("\n");
      out.write("  gtag('config', 'UA-150219424-1');\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\" src=\"//wcs.naver.net/wcslog.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("if(!wcs_add) var wcs_add = {};\n");
      out.write("wcs_add[\"wa\"] = \"fce44f52888e1\";\n");
      out.write("if(window.wcs) {\n");
      out.write("wcs_do();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<title>준오헤어</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/reset.css?rscVer=0333\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/common.css?rscVer=0333\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/owl.carousel.css?rscVer=0333\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/junohair/common.css?rscVer=0333\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/junohair/sub_common.css?rscVer=0333\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/jmarket.css?rscVer=0333\">\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/lib/jquery/1.12.4/jquery.min.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/owl.carousel.min.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/imagesloaded.3.2.x.pkgd.min.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/isotope.min.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/viewportchecker.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/modernizr.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/smoothscroll.js?rscVer=0333\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.junohair.com/static_resources/css/contents.display.none.css?rscVer=0333\">\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/lib/vue/2.6.10/vue.min.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/lib/vue-the-mask/vue-the-mask.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/lib/babel-polyfill/7.4.4/polyfill.min.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/lib/axios/0.19.0/axios.min.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/common.js?rscVer=0333\"></script>\n");
      out.write("<script src=\"https://www.junohair.com/static_resources/js/common_vue.js?rscVer=0333\"></script>\n");
      out.write("<style>\n");
      out.write("	.txtbox * {line-height: 2;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div id=\"wrap\">\n");
      out.write("		\n");
      out.write("		<div id=\"header\" class=\"\">\n");
      out.write("			<div class=\"header_top\">\n");
      out.write("				<span class=\"logo\"><a href=\"#juno\" onclick=\"location.href='/'\"><img src=\"https://www.junohair.com/static_resources/images/home_icon.png\" alt=\"JUNO\"></a></span>\n");
      out.write("				<div class=\"inner\">\n");
      out.write("					<div id=\"gnb\">\n");
      out.write("						<ul>\n");
      out.write("							<li class=\"active\"><a href=\"#juno\" onclick=\"location.href='/junohair'\">JUNO HAIR</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\">JUNO ACADEMY</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\">AVENUE JUNO</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">RECRUIT</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"gotoMyjuno()\">MY JUNO</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"topCartcount\">\n");
      out.write("					<a href=\"\"><em>장바구니 수량</em></a>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"util\">\n");
      out.write("					<dl>\n");
      out.write("						<dt class=\"hide\">유틸메뉴</dt>\n");
      out.write("\n");
      out.write("						<dd class=\"login\"><a href=\"#juno\" onclick=\"location.href='/myjuno/login'\"><span>로그인</span><img src=\"https://www.junohair.com/static_resources/images/logout_icon.png\" alt=\"로그인\"></a></dd>\n");
      out.write("\n");
      out.write("					</dl>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"lang\">\n");
      out.write("					<a href=\"#juno\" onclick=\"lang_toggle()\" class=\"cur_lang\"><img src=\"https://www.junohair.com/static_resources/images/kr_n.png\" alt=\"국가 아이콘\" class=\"national\">한국어</a>\n");
      out.write("					<span class=\"lang_arr arr_down\"><img src=\"https://www.junohair.com/static_resources/images/lang_arr_down.png\" alt=\"\"></span>\n");
      out.write("					<span class=\"lang_arr arr_up\"><img src=\"https://www.junohair.com/static_resources/images/lang_arr_up.png\" alt=\"\"></span>\n");
      out.write("					<ul class=\"lang_list\">\n");
      out.write("						<li><a href=\"#juno\" onclick=\"location.href='/en/junohair'\"><img src=\"https://www.junohair.com/static_resources/images/en_n.png\" alt=\"국가 아이콘\" class=\"national\">ENG</a></li>\n");
      out.write("						<li><a href=\"#juno\" onclick=\"location.href='/cn/junohair'\"><img src=\"https://www.junohair.com/static_resources/images/cn_n.png\" alt=\"국가 아이콘\" class=\"national\">中國語</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"header_btm\">\n");
      out.write("				<div class=\"inner\">\n");
      out.write("					<h1>\n");
      out.write("						<a href=\"/junohair\">\n");
      out.write("							<img src=\"https://www.junohair.com/static_resources/images/junohair/junohair_logo_dark.png\" alt=\"JUNO HAIR\" class=\"dark\">\n");
      out.write("							<img src=\"https://www.junohair.com/static_resources/images/junohair/junohair_logo_light.png\" alt=\"JUNO HAIR\" class=\"light\">\n");
      out.write("						</a>\n");
      out.write("					</h1>\n");
      out.write("					<div class=\"lnb\">\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair/about/story'\">ABOUT</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair/salon/shop_list'\">SALON</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair/membership/policy'\">MEMBERSHIP</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair/communication/news_list'\">COMMUNICATION</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair/reservation/intro'\">RESERVATION</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair/jmarket/prodlist'\">J MARKET</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"mobile_menu_btn\">\n");
      out.write("						<a href=\"#juno\" onclick=\"m_nav();\">\n");
      out.write("							<span></span>\n");
      out.write("							<span></span>\n");
      out.write("							<span></span>\n");
      out.write("						</a>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"mobile_topCartcount\">\n");
      out.write("						<a href=\"\"><em>장바구니 수량</em></a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"mobile_nav\" style=\"display: none;\">\n");
      out.write("			<div class=\"mobile_nav_inner\">\n");
      out.write("				<div class=\"m_util\">\n");
      out.write("					<ul>\n");
      out.write("\n");
      out.write("						<li><a href=\"#juno\" onclick=\"location.href='/myjuno/login'\">로그인</a></li>\n");
      out.write("						<li><a href=\"#juno\" onclick=\"location.href='/myjuno/join_polish'\">회원가입</a></li>\n");
      out.write("	\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"mn_wrap\">\n");
      out.write("					<div class=\"lnb\">\n");
      out.write("						<ul>\n");
      out.write("							<li>\n");
      out.write("								<strong class=\"depth1\">ABOUT<div><span class=\"horizon\"></span><span class=\"vertical\"></span></div></strong>\n");
      out.write("								<dl>\n");
      out.write("									<dt class=\"hide\">ABOUT</dt>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/about/story'\">스토리</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/about/ceo'\">CEO 인사말</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/about/brand'\">브랜드</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/about/location'\">오시는길</a></dd>\n");
      out.write("								</dl>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("								<strong class=\"depth1\">SALON<div><span class=\"horizon\"></span><span class=\"vertical\"></span></div></strong>\n");
      out.write("								<dl>\n");
      out.write("									<dt class=\"hide\">SALON</dt>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/salon/shop_list'\">살롱 소개</a></dd>\n");
      out.write("\n");
      out.write("								</dl>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("								<strong class=\"depth1\">MEMBERSHIP<div><span class=\"horizon\"></span><span class=\"vertical\"></span></div></strong>\n");
      out.write("								<dl>\n");
      out.write("									<dt class=\"hide\">MEMBERSHIP</dt>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/membership/policy'\">멤버십 제도</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/membership/partnercard'\">제휴 할인 카드</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/membership/mobilecoupon'\">모바일 쿠폰</a></dd>\n");
      out.write("								</dl>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("								<strong class=\"depth1\">COMMUNICATION<div><span class=\"horizon\"></span><span class=\"vertical\"></span></div></strong>\n");
      out.write("								<dl>\n");
      out.write("									<dt class=\"hide\">COMMUNICATION</dt>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/communication/news_list'\">NEWS</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/communication/qna'\">Q&amp;A</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"location.href='/junohair/communication/partnership'\">제휴문의</a></dd>\n");
      out.write("								</dl>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("								<strong class=\"depth1\"><a href=\"#juno\" onclick=\"location.href='/junohair/reservation/intro'\">RESERVATION</a></strong>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("								<strong class=\"depth1\"><a href=\"#juno\" onclick=\"location.href='/junohair/jmarket/prodlist'\">J MARKET</a></strong>\n");
      out.write("							</li>\n");
      out.write("							<li>\n");
      out.write("							</li><li>\n");
      out.write("								<strong class=\"depth1\">MY JUNO<div><span class=\"horizon\"></span><span class=\"vertical\"></span></div></strong>\n");
      out.write("								<dl>\n");
      out.write("									<dt class=\"hide\">MY JUNO</dt>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"gotoMyjunoMbr()\">회원정보</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"gotoMyjunoUL()\">이용내역</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"gotoMyjunoOL()\">구매내역</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"gotoMyjunoSS()\">정기배송 설정</a></dd>\n");
      out.write("									<dd><a href=\"#juno\" onclick=\"gotoMyjunoWD()\">회원 탈퇴</a></dd>\n");
      out.write("								</dl>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"gnb\">\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junohair'\"><img class=\"hair\" src=\"https://www.junohair.com/static_resources/images/m_gnb_hair.png\" alt=\"JUNO HAIR\"></a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\"><img class=\"academy\" src=\"https://www.junohair.com/static_resources/images/m_gnb_academy.png\" alt=\"JUNO ACADEMY\"></a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\"><img class=\"avenue\" src=\"https://www.junohair.com/static_resources/images/m_gnb_avenue.png\" alt=\"AVENUE JUNO\"></a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='https://www.triamilia.com/'\"><img class=\"tria\" src=\"https://www.junohair.com/static_resources/images/m_gnb_tria.png\" alt=\"TRIA MILIA\"></a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">RECRUIT</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/en/junohair/'\">ENGLISH</a></li>\n");
      out.write("							<li><a href=\"#juno\" onclick=\"location.href='/cn/junohair/'\">中国</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<script>\n");
      out.write("		/*\n");
      out.write("		function gotoMyjuno(){\n");
      out.write("			if(\"\" != \"CUST\"){\n");
      out.write("				alert(\"로그인후 이용이 가능합니다.\");\n");
      out.write("			}\n");
      out.write("			location.href = \"/myjuno/member_info\";\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function gotoMyjunoMbr(){\n");
      out.write("			if(\"\" != \"CUST\"){\n");
      out.write("				alert(\"로그인후 이용이 가능합니다.\");\n");
      out.write("			}\n");
      out.write("			location.href = \"/myjuno/member_info\";\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function gotoMyjunoUL(){\n");
      out.write("			if(\"\" != \"CUST\"){\n");
      out.write("				alert(\"로그인후 이용이 가능합니다.\");\n");
      out.write("			}\n");
      out.write("			location.href = \"/myjuno/use_list\";\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function gotoMyjunoOL(){\n");
      out.write("			if(\"\" != \"CUST\"){\n");
      out.write("				alert(\"로그인후 이용이 가능합니다.\");\n");
      out.write("			}\n");
      out.write("			location.href = \"/myjuno/order_list\";\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function gotoMyjunoSS(){\n");
      out.write("			if(\"\" != \"CUST\"){\n");
      out.write("				alert(\"로그인후 이용이 가능합니다.\");\n");
      out.write("			}\n");
      out.write("			location.href = \"/myjuno/sdelivery_set\";\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function gotoMyjunoWD(){\n");
      out.write("			if(\"\" != \"CUST\"){\n");
      out.write("				alert(\"로그인후 이용이 가능합니다.\");\n");
      out.write("			}\n");
      out.write("			location.href = \"/myjuno/withdraw\";\n");
      out.write("		}\n");
      out.write("		*/\n");
      out.write("		</script>\n");
      out.write("		<div id=\"container\">\n");
      out.write("			<div class=\"sub_visual\">\n");
      out.write("				<div class=\"sub_visual_bg\" style=\"background-image:url('https://www.junohair.com/static_resources/images/junohair/sub/jmarket/intro_visual.jpg')\"></div>\n");
      out.write("				<div class=\"sub_visual_text\">\n");
      out.write("					<strong>J MARKET</strong>\n");
      out.write("					<p class=\"sub_visual_sub_text\">\n");
      out.write("						<span>고객의 아름다움을 지원하기 위한</span><br>\n");
      out.write("						<span>뷰티 제품 전문 온라인 몰입니다</span><br>\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clear\"></div>\n");
      out.write("			<div id=\"contents\" class=\"prodviewwrap\">\n");
      out.write("				<div class=\"inner\">\n");
      out.write("					<div class=\"prodviewInfo\">\n");
      out.write("						<div class=\"detail\">\n");
      out.write("							<a href=\"#juno\" class=\"btnback\" onclick=\"gotoShop()\"><span>BACK TO SHOP</span></a>\n");
      out.write("							<h1 class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("							<p class=\"price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("							<div class=\"txtbox\">\n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"text-align: center; display: inline !important; font-family: Arial;\">\n");
      out.write("							            <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productDes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\n");
      out.write("							        </span>\n");
      out.write("							    </p>\n");
      out.write("							    <hr style=\"box-sizing: content-box; margin-top: 20px; margin-bottom: 20px; border-top-style: solid; border-top-color: rgb(221, 221, 221);\">\n");
      out.write("							    \n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"font-family: Arial;\">제품 키워드</span>\n");
      out.write("							    </p>\n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"text-align: center; display: inline !important; font-family: Arial;\">\n");
      out.write("							            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productKeyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("							        </span>\n");
      out.write("							    </p>\n");
      out.write("							    <hr style=\"box-sizing: content-box; margin-top: 20px; margin-bottom: 20px; border-top-style: solid; border-top-color: rgb(221, 221, 221);\">\n");
      out.write("							    \n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"font-family: Arial;\">추천 고객</span>\n");
      out.write("							    </p>\n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"text-align: center; display: inline !important; font-family: Arial;\">\n");
      out.write("							            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productToWho}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("							        </span>\n");
      out.write("							    </p>\n");
      out.write("							    <hr style=\"box-sizing: content-box; margin-top: 20px; margin-bottom: 20px; border-top-style: solid; border-top-color: rgb(221, 221, 221);\">\n");
      out.write("							    \n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"font-family: Arial;\">향</span>\n");
      out.write("							    </p>\n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"text-align: center; display: inline !important; font-family: Arial;\">\n");
      out.write("							            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productSmell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("							        </span>\n");
      out.write("							    </p>\n");
      out.write("							    <hr style=\"box-sizing: content-box; margin-top: 20px; margin-bottom: 20px; border-top-style: solid; border-top-color: rgb(221, 221, 221);\">\n");
      out.write("							    \n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"font-family: Arial;\">주요 성분</span>\n");
      out.write("							    </p>\n");
      out.write("							    <p style=\"margin-bottom: 10px; border-style: solid; border-color: rgb(229, 231, 235);\">\n");
      out.write("							        <span style=\"text-align: center; display: inline !important; font-family: Arial;\">\n");
      out.write("							            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productIngr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("							        </span>\n");
      out.write("							    </p>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("							<div class=\"bottombtns\">\n");
      out.write("								<div class=\"btnbox\">\n");
      out.write("								    <select id=\"productQuantity\" type=\"number\" class=\"selectarr\">\n");
      out.write("								        <option value=\"1\">1</option>\n");
      out.write("								        <option value=\"2\">2</option>\n");
      out.write("								        <option value=\"3\">3</option>\n");
      out.write("								        <option value=\"4\">4</option>\n");
      out.write("								        <option value=\"5\">5</option>\n");
      out.write("								    </select>\n");
      out.write("								    <form action=\"./addCart\" method=\"post\" id=\"addToCartForm\">\n");
      out.write("								        <input type=\"hidden\" name=\"productType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("								        <input type=\"hidden\" name=\"productId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("								        <input type=\"hidden\" name=\"productQuantity\" id=\"quantityInputCart\">\n");
      out.write("								        <button class=\"btnbuy\" type=\"submit\">장바구니</button>\n");
      out.write("								    </form>\n");
      out.write("								    <form action=\"./buyNow\" method=\"post\" id=\"buyNowForm\">\n");
      out.write("								        <input type=\"hidden\" name=\"productType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("								        <input type=\"hidden\" name=\"productId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("								        <input type=\"hidden\" name=\"productQuantity\" id=\"quantityInputBuyNow\">\n");
      out.write("								        <button class=\"btnbuy\" type=\"submit\">바로 구매</button>\n");
      out.write("								    </form>\n");
      out.write("								</div>\n");
      out.write("								\n");
      out.write("								<script>\n");
      out.write("								document.getElementById('productQuantity').addEventListener('change', updateQuantityInputs);\n");
      out.write("								\n");
      out.write("								function updateQuantityInputs() {\n");
      out.write("								    var quantity = document.getElementById('productQuantity').value;\n");
      out.write("								    document.getElementById('quantityInputCart').value = quantity;\n");
      out.write("								    document.getElementById('quantityInputBuyNow').value = quantity;\n");
      out.write("								}\n");
      out.write("								\n");
      out.write("								document.getElementById('addToCartForm').addEventListener('submit', function() {\n");
      out.write("								    updateQuantityInputs();\n");
      out.write("								});\n");
      out.write("								\n");
      out.write("								document.getElementById('buyNowForm').addEventListener('submit', function() {\n");
      out.write("								    updateQuantityInputs();\n");
      out.write("								});\n");
      out.write("								</script>\n");
      out.write("\n");
      out.write("								<div class=\"popbtns_group\">\n");
      out.write("									<a href=\"#none\" class=\"sbtn_arr\" onclick=\"openPop('popSource');return false;\"><span>제품 정보 고시</span></a>\n");
      out.write("								</div>\n");
      out.write("								\n");
      out.write("								<div id=\"popSource\" class=\"pop_shopinfo\">\n");
      out.write("									<div class=\"popinner\">\n");
      out.write("										<h4>제품 정보 고시</h4>\n");
      out.write("										<a href=\"#juno\" class=\"btnclose\" onclick=\"closePop('popSource');return false;\"></a>\n");
      out.write("										<div><b>제품명</b> 트리아 밀리아 베레 플루비아 샴푸</div><div><b>용도</b> Sensitive Scalp (민감성 두피용)</div><div><b>용량</b> 250ml</div><div><b>두피타입</b> 건성 두피, 지루성 두피</div><div><b>사용기한</b>&nbsp;제조일로부터 2년 (개봉 후 1년 이내 사용 권장)</div><div><b>사용방법</b>&nbsp;<span style=\"text-align: center; display: inline !important;\">미온수로 두피와 모발을 충분히 적시고 적당량을 덜어 거품을 내고 두피와 모발에 도포 후, 다시 미온수로 충분히 헹구어 냅니다.</span></div><div><b>제조자 및 제조판매업자</b> 제품 내 별도 표기</div><div><b>제조국</b>&nbsp;대한민국</div><div><b>사용할 때 주의사항</b>&nbsp;<span style=\"text-align: center; display: inline !important;\">1. 화장품 사용 시 또는 사용 후 직사광선에 의하여 사용부위가 붉은 반점, 부어오름 또는 가려움증 등의 이상 증상이나 부작용이 있을 경우에는 전문의 등과 상담할 것 2. 상처가 있는 부위 등에는 사용을 자제할 것 3. 눈에 들어갔을 때에는 즉시 씻어낼 것 4. 사용 후 물로 씻어내지 않으면 탈모 또는 탈색의 원인이 될 수 있으므로 주의할 것 5. 보관 및 취급 시 주의사항 가) 어린이의 손이 닿지 않는 곳에 보관할 것 나) 직사광선을 피해서 보관할 것</span></div><div>품질보증기준&nbsp;<span style=\"display: inline !important;\">본 제품에 이상이 있을 경우 공정거래위원회 고시 소비자분쟁해결기준에 의하여 교환 또는 보상받을 수 있습니다.</span></div><div><b>소비자상담 전화번호</b> 070-8672-3188</div><div><b>전성분</b>&nbsp;<span style=\"text-align: center; display: inline !important;\">정제수, 다이소듐라우레스설포석시네이트, 코코-베타인, 글리세린, 포타슘코코일글리시네이트, C12-14파레스-12, 피이지-7글리세릴코코에이트, 소듐클로라이드, 피이지-120메틸글루코스디올리에이트, 향료, 폴리쿼터늄-10, 시트릭애씨드, 소듐라우릴글라이콜카복실레이트, 소듐카보네이트, 카프릴릴글라이콜, 클로페네신, 에틸헥실글리세린, 폴리쿼터늄-7, 폴리쿼터늄-73, 다이소듐이디티에이, 하이드록시프로필구아하이드록시프로필트라이모늄클로라이드, 소듐벤조에이트, 인도멀구슬나무잎추출물, 프로판다이올, 부틸렌글라이콜, 인도멀구슬나무꽃추출물, 테트라소듐이디티에이, 병풀추출물, 황금추출물, 호장근뿌리추출물, 귤껍질추출물, 녹차추출물, 스페인감초뿌리추출물, 마트리카리아꽃추출물, 로즈마리잎추출물, 시트로넬올, 리모넨, 제라니올, 리날룰</span></div>\n");
      out.write("									</div>\n");
      out.write("									<button class=\"lbtn_black\" onclick=\"closePop('popSource');return false;\">뒤로 가기</button>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						<div>\n");
      out.write("							<div class=\"mo_topbtn\">\n");
      out.write("								<div><a href=\"#juno\" class=\"btnback\" onclick=\"gotoShop()\"><span>BACK TO SHOP</span></a></div>\n");
      out.write("								<div><a href=\"#juno\" class=\"msbtn sbtn_arr\" onclick=\"openPop('popSource');return false;\"><span>제품 정보 고시</span></a></div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"prodslideImg owl-carousel owl-theme owl-loaded\">\n");
      out.write("\n");
      out.write("							<div class=\"owl-stage-outer\"><div class=\"owl-stage\" style=\"transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 1036px;\"><div class=\"owl-item active\" style=\"width: 518px; margin-right: 0px;\"><div class=\"img\" style=\"background-image:url(https://raw.githubusercontent.com/moonjaewook/Juno/master/src/main/resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productImg1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("									<img src=\"https://raw.githubusercontent.com/moonjaewook/Juno/master/src/main/resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productImg1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\n");
      out.write("								</div></div><div class=\"owl-item\" style=\"width: 518px; margin-right: 0px;\"><div class=\"img\" style=\"background-image:url(https://raw.githubusercontent.com/moonjaewook/Juno/master/src/main/resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productImg2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("									<img src=\"https://raw.githubusercontent.com/moonjaewook/Juno/master/src/main/resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productImg2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\n");
      out.write("								</div></div></div></div><div class=\"owl-controls\"><div class=\"owl-nav\"><div class=\"owl-prev\" style=\"display: none;\">prev</div><div class=\"owl-next\" style=\"display: none;\">next</div></div><div class=\"owl-dots\" style=\"\"><div class=\"owl-dot active\"><span></span></div><div class=\"owl-dot\"><span></span></div></div></div></div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<!-- \n");
      out.write("					<div class=\"prodrelated\">\n");
      out.write("						<div class=\"ttl\"><span>RELATED PRODUCTS</span></div>\n");
      out.write("						<div>\n");
      out.write("							<a href=\"#juno\" onclick=\"location.href='/junohair/jmarket/prodview?idx=5'\" class=\"producthover\">\n");
      out.write("								<div class=\"cnt\">\n");
      out.write("									<div class=\"prodthum\" style=\"background-image:url(/upload/marketproduct/202308/3f52d0cb8e0b4668a0030f7e6c5fe9ee.jpg);\"></div>\n");
      out.write("									<div class=\"prodinfo\">\n");
      out.write("										<div><span class=\"label\">포스트 플루비아 250ml - 지성두피용 샴푸</span></div>\n");
      out.write("										<span class=\"price\">32,000</span>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</a>\n");
      out.write("							<a href=\"#juno\" onclick=\"location.href='/junohair/jmarket/prodview?idx=9'\" class=\"producthover\">\n");
      out.write("								<div class=\"cnt\">\n");
      out.write("									<div class=\"prodthum\" style=\"background-image:url(/upload/marketproduct/202308/199a1abde80949b7a05b18967077e588.jpg);\"></div>\n");
      out.write("									<div class=\"prodinfo\">\n");
      out.write("										<div><span class=\"label\">베레 플루비아 600ml - 민감성 두피용 샴푸</span></div>\n");
      out.write("										<span class=\"price\">65,000</span>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					 -->\n");
      out.write("					 \n");
      out.write("					<div class=\"prodviewEdit\">\n");
      out.write("						<img src=\"https://raw.githubusercontent.com/moonjaewook/Juno/master/src/main/resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productDetailImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<!-- 2020-05-21 모바일 상품상세설명 -->\n");
      out.write("					<div class=\"mobile_prodviewEdit\">\n");
      out.write("						<img src=\"https://raw.githubusercontent.com/moonjaewook/Juno/master/src/main/resources/productupload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.productDetailImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\n");
      out.write("					</div>\n");
      out.write("					<!-- //2020-05-21 모바일 상품상세설명 -->\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("			<div id=\"footer\">\n");
      out.write("				<div class=\"footgotop\" id=\"goTop\"><a href=\"#juno\" onclick=\"goTopbtn()\"><span class=\"blind\">상단으로 가기</span></a></div>\n");
      out.write("				<div class=\"footer_top\">\n");
      out.write("					<div class=\"inner\">\n");
      out.write("						<div class=\"ft_left\">\n");
      out.write("							<div class=\"family_site\">\n");
      out.write("								<img src=\"https://www.junohair.com/static_resources/images/family_site.png\" alt=\"family site\">\n");
      out.write("								<span class=\"bar\"></span>\n");
      out.write("								<ul class=\"fs_list\">\n");
      out.write("									<li><a href=\"#juno\" onclick=\"location.href='/junohair'\"><img src=\"https://www.junohair.com/static_resources/images/family_junoHair.png\" alt=\"JUNO HAIR\"></a></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"location.href='/junoacademy'\"><img src=\"https://www.junohair.com/static_resources/images/family_junoAcademy.png\" alt=\"JUNO ACADEMY\"></a></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"location.href='/avenuejuno'\"><img src=\"https://www.junohair.com/static_resources/images/family_junoAvenue.png\" alt=\"JUNO AVENUE\"></a></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"location.href='https://www.triamilia.com/'\"><img src=\"https://www.junohair.com/static_resources/images/family_triamilia.png\" alt=\"triamilia\"></a></li> \n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"terms\">\n");
      out.write("								<ul class=\"term_list\">\n");
      out.write("									<li><a href=\"#juno\" onclick=\"window.open('/myjuno/privacypolicy?section=1', '_blank');\">이용약관</a></li>\n");
      out.write("									<li><span class=\"bar\"></span></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"window.open('/myjuno/privacypolicy?section=2', '_blank');\">개인정보처리방침</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"ft_right\">\n");
      out.write("							<div class=\"ft_rightTop\">\n");
      out.write("								<ul>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"location.href='/junohair/communication/partnership'\">제휴문의</a></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"location.href='/recruit'\">인재채용</a></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"location.href='/junohair/communication/qna'\">Q&amp;A</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"fr_rightBottom\">\n");
      out.write("								<strong><img src=\"https://www.junohair.com/static_resources/images/junohair/footer_media_img.png\" alt=\"JUNO SOCIAL MEDIA\"><span class=\"bar\"></span></strong>\n");
      out.write("								<ul>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"window.open('https://www.facebook.com/junohair.official/', '_blank');\"><img src=\"https://www.junohair.com/static_resources/images/junohair/footer_social1.jpg\" alt=\"facebook\"></a></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"window.open('https://www.instagram.com/junohair_official/', '_blank');\"><img src=\"https://www.junohair.com/static_resources/images/junohair/footer_social2.jpg\" alt=\"instagram\"></a></li>\n");
      out.write("									<li><a href=\"#juno\" onclick=\"window.open('https://www.youtube.com/channel/UCwmPMC_aCMskDKR6P30pn6Q/', '_blank');\"><img src=\"https://www.junohair.com/static_resources/images/junohair/footer_social_youtube.jpg\" alt=\"youtube\"></a></li>\n");
      out.write("								</ul>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"footer_btm\">\n");
      out.write("					<div class=\"inner\">\n");
      out.write("						<strong><img src=\"https://www.junohair.com/static_resources/images/junohair/footer_junohair_logo.png\" alt=\"JUNO HAIR\"></strong>\n");
      out.write("						<div class=\"address\">\n");
      out.write("							<p>\n");
      out.write("								<span>(주)준오뷰티</span>\n");
      out.write("								<span>대표자 강윤선</span>	\n");
      out.write("								<span>서울특별시 강남구 청담동 63-14 JUNO &amp; BEAUTY 5층</span>	\n");
      out.write("							</p>\n");
      out.write("							<p>\n");
      out.write("								<span>사업자등록번호 : 110-81-60003</span>\n");
      out.write("								<span>통신판매번호 : 2020-서울강남-02683호</span>\n");
      out.write("								<span>대표전화 +82-2-548-0605</span>\n");
      out.write("							</p>\n");
      out.write("							<p>Copyright ⓒ 2017 JUNOHAIR.COM. All rights Reserved.</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"emblem\">\n");
      out.write("							<img src=\"https://www.junohair.com/static_resources/images/K_BPI_2020.png\" alt=\"2020 K-BPI 파워엠블렘\" style=\"height:44px\">  <!-- 2020-04-02 이미지경로 수정-->\n");
      out.write("							<img src=\"https://www.junohair.com/static_resources/images/naward.png\" alt=\"2017 &amp;Award\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>		\n");
      out.write("	</div>\n");
      out.write("	<div id=\"miniCartbox\" class=\"miniCartbox active\">\n");
      out.write("	    <div class=\"box\">\n");
      out.write("	        <div>\n");
      out.write("	            <div class=\"head\">\n");
      out.write("	                <h2 class=\"ttl\">J MARKET</h2>\n");
      out.write("	                <span class=\"price\"></span>\n");
      out.write("	            </div>\n");
      out.write("	            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	        </div>	        \n");
      out.write("	    </div>\n");
      out.write("	    <a href=\"./purchase\" class=\"lbtn_black\">구매하기</a>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("/*\n");
      out.write("	var minicart_app = new Vue({\n");
      out.write("		el : \"#miniCartbox\",\n");
      out.write("		data : {\n");
      out.write("			cartProductList : [],\n");
      out.write("			totalProductAmt : \"\",\n");
      out.write("		},\n");
      out.write("		mounted : function(){\n");
      out.write("			this.getCartInfo();\n");
      out.write("		},\n");
      out.write("		methods : {\n");
      out.write("			getCartInfo : function(mode){\n");
      out.write("				var params = {\n");
      out.write("						siteGubun : \"1\",\n");
      out.write("					}\n");
      out.write("				cf_call(\"/market/getCartInfo\", params, function(data){ minicart_app.getCartInfoCB(data, mode)} );\n");
      out.write("			},\n");
      out.write("			getCartInfoCB : function(data, mode){\n");
      out.write("				this.cartProductList = data.cartProductList;\n");
      out.write("				for(var i=0; i<this.cartProductList.length; i++){\n");
      out.write("					this.cartProductList[i].file1Style = \"background-image:url(\" + this.cartProductList[i].file1 + \")\";\n");
      out.write("					this.cartProductList[i].cntSlider = this.getCntSlider(this.cartProductList[i].productCnt)\n");
      out.write("				}\n");
      out.write("				this.totalProductAmt = data.totalProductAmt;\n");
      out.write("				\n");
      out.write("				if(mode === \"show\"){\n");
      out.write("					minicartopen();\n");
      out.write("				}\n");
      out.write("			},\n");
      out.write("			getCntSlider : function(productCnt){\n");
      out.write("				var cntSlider = [];\n");
      out.write("				productCnt = Number(productCnt);\n");
      out.write("				if(productCnt <= 5) {\n");
      out.write("					productCnt = 5;\n");
      out.write("				}\n");
      out.write("				for(var i = productCnt-4; i<=productCnt+5; i++){\n");
      out.write("					var cnt = {};\n");
      out.write("					cnt.value = i;\n");
      out.write("					cnt.code = i;\n");
      out.write("					cntSlider.push(cnt);\n");
      out.write("				}\n");
      out.write("				return cntSlider;\n");
      out.write("			},\n");
      out.write("			productCntChange01 : function(data){\n");
      out.write("				var params = {\n");
      out.write("						productIdx : data.productIdx,\n");
      out.write("						productCnt : data.productCnt,\n");
      out.write("						mode : \"set\",\n");
      out.write("						siteGubun : \"1\",\n");
      out.write("					}\n");
      out.write("				cf_call(\"/market/add2Cart\", params, this.productCntChange01CB);\n");
      out.write("			},\n");
      out.write("			productCntChange01CB : function(data){\n");
      out.write("				this.getCartInfo();\n");
      out.write("			},\n");
      out.write("			delCartProduct : function(data){\n");
      out.write("				var params = {\n");
      out.write("						productIdx : data.productIdx,\n");
      out.write("						siteGubun : \"1\",\n");
      out.write("					}\n");
      out.write("				cf_call(\"/market/delCartProduct\", params, this.delCartProductCB);\n");
      out.write("			},\n");
      out.write("			delCartProductCB : function(data){\n");
      out.write("				this.getCartInfo();\n");
      out.write("			},\n");
      out.write("			gotoBuyFromMiniCart01 : function(data){\n");
      out.write("				location.href = \"/junohair/jmarket/order_detail\";\n");
      out.write("			},\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("*/\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("// 	function openPop(id){\n");
      out.write("// 		var _this = $('#' + id);\n");
      out.write("// 		_this.show();\n");
      out.write("// 	}\n");
      out.write("	\n");
      out.write("// 	function closePop(id){\n");
      out.write("// 		var _this = $('#' + id);\n");
      out.write("// 		_this.hide();\n");
      out.write("// 	}\n");
      out.write("	\n");
      out.write("	$(function(){\n");
      out.write("		$('.prodslideImg').owlCarousel({\n");
      out.write("			items:1\n");
      out.write("		});\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("	function add2Cart(){\n");
      out.write("		var params = {\n");
      out.write("				productIdx : \"6\",\n");
      out.write("				productCnt : $(\"#productCnt\").val(),\n");
      out.write("				mode : \"add\",\n");
      out.write("				siteGubun : \"1\",\n");
      out.write("			}\n");
      out.write("		cf_call(\"/market/add2Cart\", params, add2CartCB);\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	var isCartAddes = false;\n");
      out.write("	function add2CartCB(data){\n");
      out.write("		minicart_app.getCartInfo('show');\n");
      out.write("		isCartAddes = true;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function gotoBuy(){\n");
      out.write("		if(isCartAddes){\n");
      out.write("			location.href = \"/junohair/jmarket/order_detail\";\n");
      out.write("		} else {\n");
      out.write("			var params = {\n");
      out.write("					productIdx : \"6\",\n");
      out.write("					productCnt : $(\"#productCnt\").val(),\n");
      out.write("					mode : \"add\",\n");
      out.write("					siteGubun : \"1\",\n");
      out.write("				}\n");
      out.write("			cf_call(\"/market/add2Cart\", params, gotoBuyCB);\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function gotoBuyCB(data){\n");
      out.write("		location.href = \"/junohair/jmarket/order_detail\";\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function gotoShop(){\n");
      out.write("		location.href = \"/junohair/jmarket/prodlist?catagoryMst=\";\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/market/productDetail.jsp(506,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/market/productDetail.jsp(506,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/market/productDetail.jsp(506,13) '${sessionScope.cart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.cart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	                <div class=\"prodorder\">\n");
            out.write("	                    <div class=\"prodthum\" style=\"background-image: url('https://raw.githubusercontent.com/moonjaewook/Juno/master/src/main/resources/productupload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.productImg1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\"></div>\n");
            out.write("	                    <div class=\"prodinfo\">\n");
            out.write("	                        <p class=\"prodname\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("	                        <div class=\"countChk\">\n");
            out.write("	                            <p class=\"quantity\">수량: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("	                            <p class=\"price\">단가: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("원</p>	                            \n");
            out.write("	                        </div>\n");
            out.write("	                    </div>\n");
            out.write("	                    <a href=\"/juno/deleteCart?ptype=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.productType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn_delete\"><span class=\"blind\">상품 삭제</span></a>\n");
            out.write("	                </div>\n");
            out.write("	            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
